// Traditional Chinese copy for the shell (Spec 074 user story 29).
// Every user-facing string lives here; no hardcoded text in components.
export const COPY = {
  appName: "顯恩堂系統",
  // Official full church title used as the primary brand string in headers
  // (Spec 079 §1: shorter marks are legacy shorthand only).
  appFullName: "中國基督教播道會顯恩堂",
  skipToContent: "跳到主要內容",
  login: {
    title: "登入",
    upgradeTitle: "設定新密碼",
    usernameLabel: "用戶名稱",
    passwordLabel: "密碼",
    legacyPasswordLabel: "舊 PIN 碼",
    newPasswordLabel: "新密碼",
    submit: "登入",
    submitting: "登入中…",
    upgradeSubmit: "設定新密碼並登入",
    upgrading: "設定中…",
    error: "用戶名稱或密碼不正確。",
    upgradeRequired: "此帳戶需要先設定新密碼才能登入。",
    networkError: "無法連接伺服器，請檢查網路後再試。",
    success: "登入成功。",
    guestCheckIn: "訪客簽到",
  },
  attendance: {
    title: "簽到",
    inputLabel: "課程 QR 代碼或聚會手動代碼",
    inputPlaceholder: "輸入代碼",
    resolve: "查找聚會",
    resolving: "查找中…",
    chooseEvent: "選擇聚會",
    noEvents: "目前沒有可簽到的聚會。",
    memberSubmit: "確認簽到",
    guestTitle: "訪客簽到",
    guestName: "姓名",
    guestPhone: "電話",
    guestFields: "訪客資料",
    guestPhoneHint: "例如：9123 4567 或 +852 9123 4567",
    guestSubmit: "送出訪客簽到",
    success: "簽到成功。",
    duplicate: "你已完成此聚會簽到。",
    guestDuplicate: "此電話已簽到。如需協助，請聯絡聚會負責人。",
    eventCancelled: "此聚會已取消，不能簽到。",
    eventClosed: "簽到時間已結束或尚未開始。",
    invalidEntry: "請從有效的 QR 或聚會代碼進入簽到。",
    enrollmentRequired: "報名狀態不符合簽到條件。",
    rateLimited: "請求過於頻繁，請稍後再試。",
    eventTime: "聚會時間",
    signedOutNote: "訪客不需要登入。",
    loginForMember: "登入後以成員身份簽到",
    operatorTitle: "聚會簽到管理",
    eventId: "聚會 ID",
    memberSearch: "搜尋已報名成員",
    memberSearchEmpty: "找不到符合的成員。",
    search: "搜尋",
    checkInMember: "替成員簽到",
    roster: "簽到名單",
    void: "取消簽到",
    voidReason: "取消原因",
    correctGuest: "修正訪客資料",
    correctionReason: "修正原因",
    saveCorrection: "儲存修正",
    printSheet: "列印聚會簽到表",
    camera: "使用相機掃描 QR",
    cameraClose: "關閉相機",
    cameraRetry: "重試相機",
    cameraUnavailable: "相機不可用，請使用手動代碼。",
    assistedOpen: "開協助簽到",
    status: {
      Active: "有效",
      Voided: "已作廢",
    },
    method: {
      self_qr_scan: "成員掃描 QR",
      self_manual_code: "成員手動代碼",
      leader_qr_scan: "負責人掃描 QR",
      leader_manual_search: "負責人手動搜尋",
      guest_qr_scan: "訪客掃描 QR",
      guest_manual_code: "訪客手動代碼",
    },
    sheetMethod: "簽到方法",
    sheetScanInstruction: "請使用手機相機掃描 QR 碼以簽到",
    sheetManualCode: "聚會手動代碼",
  },
  profile: {
    title: "個人檔案",
    name: "姓名",
    username: "用戶名稱",
    phone: "電話",
    role: "角色",
    status: "狀態",
    qrCode: "QR Code",
    qrEmpty: "目前沒有 QR 資料。",
    accountSettings: "帳戶資料",
    accountSettingsHint: "更新用戶名稱或密碼。",
  },
  restore: {
    loading: "正在還原工作階段…",
    restored: "工作階段已還原。",
    expired: "工作階段已過期，請重新登入。",
  },
  logout: {
    submit: "登出",
    error: "登出時發生錯誤，但已安全終止工作階段。",
    failedNotice: "登出請求失敗，但本機工作階段已清除。",
    success: "已登出。",
    forbiddenAction: "登出並返回登入",
  },
  account: {
    updatedNotice: "帳戶資料已更新，請重新登入。",
  },
  sections: {
    home: "首頁",
    profile: "個人檔案",
    programs: "課程與活動",
    events: "聚會管理",
    scanner: "掃描簽到",
    care: "關懷儀表板",
    permissions: "權限管理",
    // S10 heading: distinguishes the permissions SECTION label from the
    // page title (roles + permissions table, Spec #079 §S10).
    permissionsHeading: "權限與角色管理",
    placeholder: "內容建置中。",
  },
  nav: {
    backToHome: "返回首頁",
    backToProfile: "返回個人檔案",
    loading: "載入中…",
    unauthorized: "您沒有權限存取此頁面。",
    unknownRoute: "找不到此頁面。",
    label: "主要導航",
  },
  error: {
    networkError: "無法連接伺服器，請檢查網路後再試。",
    unavailable: "系統暫時無法使用，請稍後再試。",
    serverError: "伺服器發生錯誤，請稍後再試。",
    forbidden: "您沒有權限執行此操作。",
    validation: "輸入資料無效，請檢查後再試。",
    notFound: "找不到請求的資料。",
    conflict: "資料衝突，請重新整理後再試。",
    malformed: "伺服器回應格式錯誤。",
    unknown: "發生未知錯誤。",
    retry: "重試連接",
  },
  empty: {
    courseData: "目前沒有課程資料。",
    title: "無資料",
  },
  programs: {
    pageTitle: "課程與活動",
    lead: "先選部門，再處理課程、聚會或報名。",
    entryLead: "課程與活動集中於此，先了解適合你的下一步。",
    participantMode: "參與者模式",
    participantLead: "探索課程與活動，了解適合你的下一步。",
    managementMode: "管理模式",
    managementLead: "只顯示你目前獲授權範圍內的管理入口。",
    modeLabel: "課程模式",
    enterManagement: "進入管理模式",
    enterParticipant: "返回參與者模式",
    backToEntry: "返回課程入口",
    accessLoading: "正在確認管理權限…",
    managementScopeReady: "你的管理範圍已確認。",
    managementBoundaryHint:
      "目前只確認你的管理範圍；實際管理操作會在管理工作區提供。",
    managementDirectoryTitle: "管理課程目錄",
    managementDirectoryLead:
      "只列出你目前可操作的課程；你可以按課程名稱、類別或部門搜尋。",
    managementDirectorySearchLabel: "搜尋可管理課程",
    managementDirectorySearchPlaceholder: "搜尋課程名稱、簡介、類別或部門",
    managementDirectoryClearSearch: "清除搜尋",
    managementDirectoryListLabel: "可管理課程",
    managementDirectoryLoading: "正在載入管理課程目錄…",
    managementDirectoryLoadError: "無法載入管理課程目錄",
    managementDirectoryForbidden: "無法載入管理課程目錄",
    managementDirectoryForbiddenHint: "你的管理範圍可能已變更，請重新確認。",
    managementDirectoryRetry: "重試載入管理課程目錄",
    managementDirectoryEmpty: "目前沒有可管理的課程",
    managementDirectoryEmptyHint: "獲授權的課程會在這裡顯示。",
    managementDirectoryNoMatches: "找不到符合的可管理課程",
    managementDirectoryNoMatchesHint: "請清除搜尋，或嘗試其他關鍵字。",
    managementScopeDepartment: "部門範圍",
    managementScopeProgram: "指定課程",
    workspaceTitle: "課程工作區",
    workspaceLead: "先確認課程狀態，再進入一項明確的管理工作。",
    workspaceBack: "返回管理課程目錄",
    workspaceLoading: "正在載入課程工作區…",
    workspaceLoadError: "無法載入課程工作區",
    workspaceForbidden: "無法進入課程工作區",
    workspaceUnavailable: "課程管理範圍已失效",
    workspaceUnavailableHint:
      "這個課程目前不可用，或你的管理範圍已被撤回。請返回管理課程目錄。",
    workspaceRetry: "重試載入課程工作區",
    workspaceSummaryLoading: "正在載入工作區摘要…",
    workspaceSummaryUnavailable: "摘要資料暫時不可用。",
    workspaceIdentity: "課程資料",
    workspaceDescription: "簡介",
    workspaceCategory: "類別",
    workspaceDepartment: "所屬部門",
    workspaceBehavior: "形式",
    workspaceLifecycle: "狀態",
    workspaceDiscoverability: "可見性",
    workspaceEnrollmentMode: "報名方式",
    workspaceNearestEvent: "最近聚會",
    workspaceNearestEventNone: "目前沒有可用的聚會資料。",
    workspaceAttention: "需要留意",
    workspacePendingRequests: "待處理報名",
    workspaceActiveParticipants: "活躍參與者",
    workspaceNoAttention: "目前沒有待處理項目。",
    workspaceTaskLabel: "管理工作",
    workspaceTaskEvents: "聚會",
    workspaceTaskParticipants: "參與者",
    workspaceTaskSettings: "課程設定",
    workspaceTaskEventsLead:
      "查看這個課程的聚會記錄；建立聚會並於聚會詳情中編輯。",
    workspaceTaskParticipantsLead:
      "查看報名申請與活躍參與者；決定與新增操作由參與者工作流程處理。",
    workspaceTaskSettingsLead: "查看目前課程設定與可用的管理能力。",
    workspaceTaskEventsLoading: "正在載入聚會…",
    workspaceTaskEventsError: "無法載入聚會",
    workspaceTaskEventsRetry: "重試載入聚會",
    workspaceTaskEventsEmpty: "目前沒有聚會。",
    workspaceTaskParticipantsLoading: "正在載入參與者資料…",
    workspaceTaskParticipantsError: "無法載入參與者資料",
    workspaceTaskParticipantsRetry: "重試載入參與者資料",
    workspaceTaskParticipantsEmpty: "目前沒有報名或活躍參與者。",
    workspaceTaskSettingsCapabilities: "目前能力",
    workspaceTaskSettingsNoCapabilities: "目前沒有可用的課程管理能力。",
    workspaceTaskUnavailable: "這項工作目前未在所屬部門啟用。",
    workspaceCapabilityManage: "課程管理",
    workspaceCapabilityPublish: "發佈課程",
    workspaceCapabilityLeaderAssign: "委派負責人",
    noManagementScope: "沒有管理範圍",
    noManagementScopeHint: "目前沒有可用的課程管理範圍。",
    managementForbidden: "無法進入管理模式",
    managementForbiddenHint: "你沒有權限進入這個管理範圍。",
    malformedIntent: "連結資料無效",
    malformedIntentHint: "請返回課程入口，再開啟有效的活動連結。",
    directProgramIntent: "已保留活動連結",
    directProgramIntentHint: "活動內容會在課程任務中開啟；目前先保留你的連結。",
    detailBack: "返回課程目錄",
    detailLoading: "正在載入課程內容…",
    detailLoadError: "無法載入課程內容",
    detailRetry: "重試載入課程內容",
    detailUnavailable: "無法開啟這個課程",
    detailUnavailableHint:
      "這個課程目前不可用，或你未有權限查看。請返回課程目錄。",
    detailPurpose: "課程簡介",
    detailBehavior: "形式",
    detailLifecycle: "狀態",
    detailParticipation: "參與方式",
    detailDepartment: "所屬部門",
    detailCategory: "類別",
    detailSchedule: "時間安排",
    detailScheduleNone: "目前未提供固定時間安排。",
    detailEvents: "近期活動",
    detailEventsNone: "目前沒有即將進行的活動。",
    detailEventTime: "活動時間",
    detailBehaviorRecurring: "Recurring · 定期",
    detailBehaviorOneOff: "OneOff · 單次",
    detailLifecycleDraft: "Draft · 草稿",
    detailLifecycleActive: "Active · 啟用",
    detailLifecycleArchived: "Archived · 已存檔",
    detailParticipationMemberRequest: "MemberRequest · 可報名",
    detailParticipationManagerOnly: "ManagerOnly · 僅限負責人",
    scheduleDays: ["日", "一", "二", "三", "四", "五", "六"],
    retryAccess: "重試確認管理權限",
    catalogLoading: "正在載入課程目錄…",
    catalogReady: "課程目錄已載入。",
    catalogEmpty: "目前沒有可用的課程",
    catalogEmptyHint: "目錄尚無開放課程。課程開放後就會顯示在這裡。",
    catalogLoadError: "無法載入課程目錄",
    catalogRetry: "重試載入課程目錄",
    catalogForbidden: "無法載入課程目錄",
    catalogForbiddenHint: "你沒有權限查看課程目錄。",
    catalogSearchLabel: "搜尋課程",
    catalogSearchPlaceholder: "搜尋課程名稱、簡介或類別",
    catalogClearSearch: "清除搜尋",
    catalogNoMatches: "找不到符合的課程",
    catalogNoMatchesHint: "試試其他關鍵字，或清除搜尋回到完整目錄。",
    catalogNoFilterMatchesHint:
      "目前的篩選沒有符合課程。清除篩選後可回到完整目錄。",
    catalogClearFilters: "清除篩選",
    catalogListLabel: "課程目錄",
    catalogFilterLifecycle: "課程狀態",
    catalogFilterParticipation: "參與方式",
    filterAll: "全部",
    filterActive: "啟用",
    filterDraft: "草稿",
    filterArchived: "已存檔",
    filterMemberRequest: "可報名",
    filterManagerOnly: "僅限負責人",
    programUnavailable: "無法開啟這個課程",
    programUnavailableHint:
      "這個課程目前不可用，或你未有權限查看。你可以繼續瀏覽其他課程。",
    programSelected: "已保留課程連結。",
    departments: "部門",
    programs: "課程與活動",
    modules: "模組",
    moduleDisabled: "此功能模組尚未啟用。請先啟用模組，相關功能才會顯示。",
    noDepartments: "目前沒有部門。新增部門後，就可以開始建立課程。",
    noPrograms: "此部門尚未有課程。啟用課程目錄後可新增。",
    createDepartment: "新增部門",
    createProgram: "新增課程",
    deptCode: "部門代碼",
    deptName: "部門名稱",
    deptCodePlaceholder: "例如：青區",
    deptNamePlaceholder: "部門名稱",
    programName: "課程名稱",
    programNamePlaceholder: "課程名稱",
    programDescription: "課程簡介",
    programCategory: "活動類別",
    programLifecycle: "課程狀態",
    programEnrollmentMode: "報名方式",
    programDisplayOrder: "顯示次序",
    programDetails: "查看課程詳情",
    programOverview: "概覽",
    programTasks: "課程工作",
    programEdit: "基本資料",
    programEvents: "聚會與時間表",
    programEnrollment: "報名",
    programLeaders: "事工負責人",
    backToOverview: "返回概覽",
    programDescriptionEmpty: "未填寫課程簡介。",
    editProgram: "編輯課程",
    saveProgram: "儲存課程",
    cancelEdit: "取消編輯",
    programCreateTitle: "新增課程",
    programCreateLead: "選擇獲授權部門，建立定期或單次課程。",
    programEditLead: "更新課程資料；儲存後會重新確認工作區內容。",
    programSaved: "課程已儲存，正在返回工作區。",
    programCreateUnavailable: "目前沒有可建立課程的部門。",
    programCreateForbidden: "你沒有在任何部門建立課程的權限。",
    programCategoryRequired: "請填寫活動類別。",
    programCreateDraftOnlyHint:
      "所選部門未獲授權發佈課程；課程會先以草稿建立。",
    programConflict: "課程名稱與現有資料衝突，請重新整理後再試。",
    programTransportAmbiguous:
      "未能確認課程是否已儲存。請重新整理工作區後再試，避免重複提交。",
    archiveBlocked:
      "課程仍有未完成的未來營運承諾，先處理相關聚會或報名後再存檔。",
    archiveProgram: "存檔課程",
    activateProgram: "啟用課程",
    behaviorType: "形式",
    behaviorRecurring: "定期",
    behaviorOneOff: "單次",
    lifecycleDraft: "草稿",
    lifecyclePending: "籌備中",
    lifecycleActive: "啟用",
    lifecycleArchived: "已存檔",
    discoverabilityListed: "公開",
    discoverabilityUnlisted: "不公開",
    moduleProgramCatalog: "課程目錄",
    moduleEnrollment: "報名",
    moduleEvents: "聚會",
    moduleAttendance: "出席",
    moduleCustomForms: "自訂表單",
    departmentSettings: "部門設定",
    departmentDetails: "部門資料",
    saveDepartment: "儲存部門",
    departmentManagers: "部門管理者",
    noDepartmentManagers: "目前沒有部門管理者。",
    assignDepartmentManager: "新增部門管理者",
    revokeDepartmentManager: "移除部門管理者",
    confirmRevokeDepartmentManager: "確定要移除此部門管理者嗎？",
    departmentManagerUserId: "選擇部門管理者",
    departmentManagerUserIdPlaceholder: "輸入姓名或用戶名稱",
    departmentManagerAssignedNotice: "已新增部門管理者。",
    departmentManagerRevokedNotice: "已移除部門管理者。",
    departmentScopeHint: "此設定只適用於目前部門，不會改變全域角色。",
    enable: "啟用",
    disable: "停用",
    expand: "展開",
    collapse: "收合",
    submit: "建立",
    submitting: "建立中…",
    created: "已建立。",
    updated: "已更新。",
    loadError: "無法載入課程與活動資料，請稍後再試。",
    events: "聚會",
    eventsEmpty: "目前沒有聚會。",
    noRules: "尚未設定時間表。",
    eventDate: "日期",
    eventTime: "時間",
    eventStatus: "狀態",
    eventActive: "進行",
    eventCancelled: "已取消",
    eventScheduleSource: "自動",
    eventManualSource: "手動",
    hkTimeMarker: "時間均以香港時間顯示（GMT+8）。",
    ruleWeekly: "每週",
    ruleMonthly: "每月",
    dayOfWeekLabel: "每週日子",
    weekdaySunday: "星期日",
    weekdayMonday: "星期一",
    weekdayTuesday: "星期二",
    weekdayWednesday: "星期三",
    weekdayThursday: "星期四",
    weekdayFriday: "星期五",
    weekdaySaturday: "星期六",
    monthDayLabel: "每月日子",
    startTime: "開始時間",
    endTime: "結束時間",
    addRule: "新增時間表",
    generateEvents: "產生聚會",
    generating: "產生中…",
    generated: "已產生 {created} 場聚會，跳過 {skipped} 場重複。",
    generateRequiresRecurring: "只有定期課程可產生聚會。",
    createEvent: "新增聚會",
    eventStart: "開始時間（香港時間）",
    eventEnd: "結束時間（香港時間）",
    cancelEvent: "取消聚會",
    cancelEventConfirm: "確定取消這場聚會嗎？取消後仍會保留記錄。",
    confirmCancelEvent: "取消聚會",
    keepEvent: "保留聚會",
    cancelReason: "取消原因",
    cancelReasonPlaceholder: "請填寫取消原因",
    eventCancelledNotice: "聚會已取消。",
    cancelledReason: "取消原因：{reason}",
    rescheduleEvent: "改期",
    confirmReschedule: "確認改期",
    rescheduleStart: "改期開始時間",
    rescheduleEnd: "改期結束時間",
    cancelOccurrence: "取消該次",
    cancelOccurrenceConfirm: "確定取消這次聚會嗎？之後可以恢復。",
    confirmCancelOccurrence: "確定取消該次",
    keepOccurrence: "保留該次",
    restoreOccurrence: "恢復該次",
    exceptionUpdatedNotice: "已更新例外。",
    exceptionRemovedNotice: "已移除例外。",
    eventRescheduledBadge: "已改期至 {time}",
    eventCancelledBadge: "本次已取消",
    eventsLoadError: "無法載入聚會資料，請稍後再試。",
    ruleCreateError: "無法新增時間表。",
    exceptionCreateError: "無法更新例外。",
    eventCreateError: "無法新增聚會。",
    generateError: "無法產生聚會。",
    enrollment: "報名",
    enrollmentModeMemberRequest: "成員申請",
    enrollmentModeManagerOnly: "管理員安排",
    requestEnroll: "申請報名",
    requestSubmitted: "已送出報名申請。",
    withdrawRequest: "撤回申請",
    requestWithdrawnNotice: "申請已撤回。",
    requests: "報名申請",
    noRequests: "目前沒有報名申請。",
    requestPending: "待處理",
    requestApproved: "已核准",
    requestRejected: "已拒絕",
    requestWithdrawn: "已撤回",
    requestSubmittedAt: "申請日期",
    approve: "核准",
    reject: "拒絕",
    decisionNote: "決定備註",
    decisionMade: "已處理申請。",
    enrollments: "報名記錄",
    noEnrollments: "目前沒有報名記錄。",
    enrollmentActive: "已加入",
    enrollmentCancelled: "已取消",
    cancelEnrollment: "取消報名",
    enrollmentCancelledNotice: "報名已取消。",
    assistedEnroll: "新增報名",
    memberId: "成員 ID",
    memberIdPlaceholder: "輸入姓名或用戶名稱",
    memberSearchHint: "輸入姓名或用戶名稱，從現有會友中選擇。",
    memberSearchLoading: "搜尋會友中…",
    memberSearchError: "暫時無法搜尋會友，請稍後再試。",
    memberSearchRetry: "重試搜尋",
    memberSearchEmpty: "找不到符合的現有會友。",
    memberSearchResults: "找到 {count} 位會友。",
    clearMember: "清除選擇",
    assistedSubmitted: "已新增報名。",
    managerOnlyNote: "此課程由管理員安排成員加入。",
    selfEnrollmentNote: "你已加入此課程。",
    enrollmentError: "報名操作失敗。",
    enrollmentHistory: "你的報名紀錄",
    enrollmentScheduleAdvisory:
      "申請前請確認時間是否適合；系統只提供提示，不會因時間重疊自動阻擋。",
    enrollmentUnavailableNote: "目前無法在此頁處理你的報名。",
    enrollmentIneligibleNote: "你目前沒有此課程的報名資格。",
    enrollmentDraftNote: "此課程尚未開放報名。",
    enrollmentArchivedNote: "此課程已存檔，不能提交新的報名。",
    enrollmentActiveHint: "你目前已加入此課程。",
    requestPendingHint: "申請已送出，等待課程負責人處理。",
    requestRejectedHint: "上次申請未獲接納；如課程仍開放，可重新申請。",
    requestWithdrawnHint: "你已撤回上次申請；如課程仍開放，可重新申請。",
    enrollmentCancelledHint: "這次報名已取消；如課程仍開放，可重新申請。",
    leaders: "事工負責人",
    noLeaders: "目前沒有事工負責人。",
    assignLeader: "新增負責人",
    revokeLeader: "移除負責人",
    confirmRevokeLeader: "確定要移除此事工負責人嗎？",
    confirmRevoke: "確定移除",
    cancelRevoke: "取消",
    leaderUserId: "選擇會友",
    leaderUserIdPlaceholder: "輸入姓名或用戶名稱",
    leaderAssignedNotice: "已新增事工負責人。",
    leaderRevokedNotice: "已移除事工負責人。",
    leaderAccountInactive:
      "無法新增：此帳戶尚未啟用。請選取狀態為「啟用」的帳戶。",
    enrollmentDuplicate: "此會友已報名此課程。",
    // EVT-01 (#251): event operational detail and independent availability.
    eventCreate: "新增聚會",
    eventCreateTitle: "聚會資料",
    eventCreateSubmit: "建立聚會",
    eventCreateCancel: "取消建立",
    eventDetailOpen: "詳情",
    eventDetailBack: "返回聚會列表",
    eventDetailTitle: "聚會詳情",
    eventDetailNotFound: "找不到此聚會。",
    eventName: "聚會名稱",
    eventNamePlaceholder: "輸入聚會名稱（可留空）",
    eventLocation: "地點",
    eventLocationPlaceholder: "輸入地點（可留空）",
    eventDetailLeaders: "事工負責人",
    eventDetailParticipantSummary: "報名與出席",
    eventActiveEnrollments: "已報名 {count} 人",
    eventCheckedIn: "已簽到 {count} 人",
    eventNoParticipants: "目前未有報名或簽到記錄。",
    eventAvailability: "開放狀態",
    eventAvailable: "開放",
    eventUnavailable: "暫停",
    eventAvailabilityDeactivate: "暫停聚會",
    eventAvailabilityActivate: "恢復開放",
    eventAvailabilityConfirmTitle: "暫停此聚會？",
    eventAvailabilityConfirmBody:
      "暫停後，已報名成員將不能簽到（{count} 項進行中的報名／簽到會受影響）。",
    eventAvailabilityConfirmProceed: "確定暫停",
    eventAvailabilityNotice: "聚會已暫停開放。",
    eventAvailabilityRestoredNotice: "聚會已恢復開放。",
    eventAvailabilityUndo: "復原",
    eventEditTitle: "編輯聚會資料",
    eventEditSave: "儲存更改",
    eventEditCancel: "取消編輯",
    eventSavedNotice: "聚會資料已更新。",
    eventCreatedNotice: "聚會已建立。",
    eventAvailabilityConfirmRequired:
      "此聚會有進行中的報名或簽到，需確認後才能暫停。",
    eventUnavailableCheckIn: "此聚會已暫停開放，不能簽到。",
    eventCheckInWindow: "簽到時間",
    eventCheckInWindowOpensAt: "開放簽到",
    eventCheckInWindowClosesAt: "結束簽到",
  },
} as const;

export function errorCopyFor(
  code?: string,
  // _detail is surfaced only for VALIDATION problems, whose server detail is
  // a specific user-facing Cantonese sentence; every other code keeps
  // centralized copy as the sole user-facing source.
  _detail?: string
): string {
  if (code === "NETWORK_ERROR") {
    return COPY.error.networkError;
  }
  if (code === "AUTH_REQUIRED") {
    return COPY.restore.expired;
  }
  if (code === "FORBIDDEN") {
    return COPY.error.forbidden;
  }
  if (code === "VALIDATION") {
    // Server VALIDATION problems carry a specific, user-facing Cantonese
    // detail (e.g. 請輸入有效電話號碼。); surface it instead of the generic
    // catch-all so the guest/member panels show why the submit was refused.
    // Other codes keep the centralized copy as the sole user-facing source.
    return _detail?.trim() ? _detail : COPY.error.validation;
  }
  if (code === "NOT_FOUND" || (code && code.endsWith("_NOT_FOUND"))) {
    return COPY.error.notFound;
  }
  if (code === "PROGRAM_ARCHIVE_BLOCKED") {
    return COPY.programs.archiveBlocked;
  }
  if (code === "CONFLICT") {
    return COPY.error.conflict;
  }
  if (code === "ACCOUNT_INACTIVE") {
    return COPY.programs.leaderAccountInactive;
  }
  if (code === "ENROLLMENT_DUPLICATE") {
    return COPY.programs.enrollmentDuplicate;
  }
  if (code === "EVENT_CANCELLED") {
    return COPY.attendance.eventCancelled;
  }
  if (code === "CHECK_IN_CLOSED") {
    return COPY.attendance.eventClosed;
  }
  if (code === "INVALID_CHECK_IN_ENTRY") {
    return COPY.attendance.invalidEntry;
  }
  if (code === "ENROLLMENT_REQUIRED") {
    return COPY.attendance.enrollmentRequired;
  }
  if (code === "RATE_LIMITED") {
    return COPY.attendance.rateLimited;
  }
  if (code === "DUPLICATE_ATTENDANCE") {
    return COPY.attendance.guestDuplicate;
  }
  if (code === "CONFIRMATION_REQUIRED") {
    return COPY.programs.eventAvailabilityConfirmRequired;
  }
  if (code === "EVENT_UNAVAILABLE") {
    return COPY.programs.eventUnavailableCheckIn;
  }
  if (code === "UNAVAILABLE") {
    return COPY.error.unavailable;
  }
  if (code === "INTERNAL_ERROR") {
    return COPY.error.serverError;
  }
  if (code === "MALFORMED_RESPONSE" || code === "MALFORMED_REQUEST") {
    return COPY.error.malformed;
  }
  return COPY.error.unknown;
}

// Traditional Chinese landing-page copy for the signed-out Persuade surface.
// Drawn from the real sections the app ships (Spec 000 / Spec 074); no
// testimonials, metrics, or security claims are invented on this surface.
export const LANDING = {
  skipToLogin: "跳到登入",
  skipToRegister: "跳到註冊表單",
  brandFull: "中國基督教播道會顯恩堂",
  brand: "顯恩堂",
  brandSystem: "系統",
  homeLabel: "顯恩堂系統首頁",
  systemDescription: "會友與教會同工的內部營運系統。",
  navLabel: "頁面導覽",
  featuresNav: "認識功能",
  loginNav: "登入",
  heroTitle: "一堂的相聚，有據可依",
  heroSub:
    "將課程報名、聚會管理、掃描簽到與關懷追蹤，收進同一本會友名冊——讓牧養有事可循，讓服事有據可查。",
  primaryCta: "立即登入",
  secondaryCta: "認識功能",
  registerTitle: "一本名冊，涵蓋一堂",
  registerLead: "以下都是顯恩堂系統實際提供的功能。",
  featurePrograms: "課程與活動",
  featureProgramsDesc: "活動與課程的報名、名單，一處掌握。",
  featureEvents: "聚會管理",
  featureEventsDesc: "定期聚會與日程安排，一目了然。",
  featureScanner: "掃描簽到",
  featureScannerDesc: "以 QR 碼即時記錄出席，無需手寫名單。",
  featureCare: "關懷儀表板",
  featureCareDesc: "把需要跟進的會友，放在事奉者眼前。",
  loginPanelLead: "使用你的用戶名稱與密碼。",
  loginAfterNote: "登入後，將進入你獲授權的功能頁面。",
  footerMotto: "一堂之務，一處安放。",
  footerNote: "顯恩堂系統 — 教會管理系統",
} as const;
