import { RpcError } from "@/lib/api";

// Traditional Chinese copy for the shell (Spec 074 user story 29).
// Every user-facing string lives here; no hardcoded text in components.
export const COPY = {
  appName: "顯恩堂系統",
  // Official full church title used as the primary brand string in headers
  // (Spec 079 §1: shorter marks are legacy shorthand only).
  appFullName: "中國基督教播道會顯恩堂",
  shell: {
    shortMark: "顯恩堂",
    roleLabels: {
      Member: "會員",
      Staff: "同工",
      Admin: "管理員",
    },
  },
  skipToContent: "跳到主要內容",
  login: {
    title: "登入",
    upgradeTitle: "設定新密碼",
    usernameLabel: "用戶名稱",
    passwordLabel: "密碼",
    legacyPasswordLabel: "舊 PIN 碼",
    newPasswordLabel: "新密碼",
    confirmPasswordLabel: "確認新密碼",
    submit: "登入",
    submitting: "登入中…",
    upgradeSubmit: "設定新密碼並登入",
    upgrading: "設定中…",
    error: "用戶名稱或密碼不正確。",
    missingFields: "請輸入登入名稱及密碼。",
    upgradeRequired: "此帳戶需要先設定新密碼才能登入。",
    upgradeLegacyPinInvalid: "請輸入有效的舊 PIN 碼。",
    upgradePasswordTooShort: "請設定最少 8 個字元的新密碼。",
    upgradePasswordMismatch: "兩次輸入的密碼不一致。",
    networkError: "未能登入。請重新連線後再試。",
    upgradeNetworkError: "未能更新。請重新連線後再試。",
    success: "登入成功。",
    guestCheckIn: "訪客簽到",
  },
  sessionExpired: {
    title: "工作階段已過期",
    message:
      "為保障帳戶安全，閒置一段時間後需要重新登入。重新登入後會返回你原本查看的頁面。",
    reLogin: "重新登入",
  },
  attendance: {
    title: "掃描",
    selfHint: "掃描課程 QR 碼或輸入聚會手動代碼。",
    modeLabel: "簽到模式",
    selfMode: "本人簽到",
    assistedMode: "協助簽到",
    operatorMode: "代為簽到",
    assistedHint: "為已報名成員簽到；請先選擇開放中的聚會。",
    assistedContext: "目前聚會",
    assistedContextHint: "只顯示你獲授權且正在開放簽到的聚會。",
    assistedAccessLoading: "正在確認協助簽到權限…",
    assistedAccessError: "暫時無法確認協助簽到權限，請稍後再試。",
    assistedNoAccess: "目前沒有可協助的開放聚會。",
    assistedContextRequired: "請先選擇聚會。",
    assistedContextStale: "此聚會已不再開放或你沒有權限，請重新選擇。",
    assistedSearchHint: "可按姓名、電話或成員 QR 碼搜尋已報名成員。",
    assistedMembersFound: "已找到符合的成員，請選擇簽到。",
    assistedMemberSearchAmbiguous: "掃描結果不唯一，請使用姓名或電話搜尋。",
    assistedRetry: "重新確認協助簽到",
    assistedBackToSelf: "返回本人簽到",
    inputLabel: "課程 QR 代碼或聚會手動代碼",
    inputPlaceholder: "輸入代碼",
    resolve: "查找聚會",
    resolving: "查找中…",
    chooseEvent: "選擇聚會",
    noEvents: "目前沒有可簽到的聚會，請稍後再試或輸入聚會手動代碼。",
    transportAmbiguous: "未能確認簽到是否完成，請重試以確認狀態。",
    retry: "重試簽到",
    eventTime: "時間",
    eventLocation: "地點",
    guestTitle: "訪客簽到",
    guestBack: "返回",
    guestLead: "輸入聚會代碼及聯絡資料，完成今次出席記錄。",
    guestCode: "聚會代碼",
    guestCodePlaceholder: "例如 482913",
    guestName: "姓名",
    guestPhone: "電話",
    guestPhoneLabel: "電話號碼",
    guestPhoneHint: "只用於今次聚會跟進。例如：9123 4567 或 +852 9123 4567",
    guestValidation: "請輸入聚會代碼、姓名及電話。",
    guestSubmit: "確認簽到",
    guestSubmitting: "送出中…",
    guestResultTitle: "訪客簽到完成",
    guestResultLead: (period: string) =>
      `歡迎參加${period}聚會。你的資料已安全提交。`,
    guestDone: "完成",
    success: "簽到成功。",
    duplicate: "你已完成此聚會簽到。",
    guestDuplicate: "此電話已簽到。如需協助，請聯絡聚會負責人。",
    eventCancelled: "此聚會已取消，不能簽到。",
    eventClosed: "簽到時間已結束或尚未開始。",
    invalidEntry: "請從有效的 QR 或聚會代碼進入簽到。",
    enrollmentRequired: "報名狀態不符合簽到條件。",
    rateLimited: "請求過於頻繁，請稍後再試。",
    loginForMember: "登入後以成員身份簽到",
    operatorTitle: "聚會簽到管理",
    eventId: "聚會 ID",
    memberSearch: "搜尋已報名成員",
    memberSearchEmpty: "找不到符合的成員。",
    search: "搜尋",
    checkInMember: "替成員簽到",
    roster: "簽到名單",
    rosterTitle: "簽到名單",
    rosterStatusActive: "開放簽到",
    checkedInCount: (count: number, total: number) =>
      `已簽到 ${count}/${total}`,
    void: "作廢簽到",
    voidAttendance: "作廢簽到",
    voidReason: "作廢原因",
    voidLead: "作廢後會保留記錄，但不再計入出席進度。",
    voidConfirm: "確認作廢",
    voidSuccess: "簽到已作廢",
    correctGuest: "修正訪客資料",
    guestCorrection: "修正訪客資料",
    correctionReason: "姓名或電話",
    correctionLead: "輸入訪客的正確姓名或電話。",
    saveCorrection: "儲存修正",
    correctionSaved: "訪客資料已修正",
    printSheet: "列印簽到表",
    exportSheet: "匯出簽到表",
    maskedPhone: (phone: string) => {
      const normalized = phone.trim().replaceAll(/[\s().-]/gu, "");
      if (normalized.length <= 4) {
        return "****";
      }
      return `${normalized.slice(0, 4)}${"*".repeat(normalized.length - 4)}`;
    },
    chooserTitle: "聚會／出席",
    chooserLead: "選擇一個開放簽到的聚會，處理出席點名及代簽。",
    chooserEmpty: "目前沒有開放簽到的聚會",
    chooserOpenMeetings: "開放簽到的聚會",
    camera: "使用相機掃描 QR",
    cameraClose: "關閉相機",
    cameraRetry: "重試相機",
    cameraUnavailable: "相機不可用，請使用手動代碼。",
    cameraOpening: "正在開啟相機…",
    cameraLiveHint: "將二維碼放入框內掃描",
    stopScan: "停止掃描",
    cameraDeniedTitle: "相機權限未開啟",
    cameraDeniedBody:
      "相機權限未開啟。請在瀏覽器設定允許相機，再按「重試相機」。",
    cameraUnsupportedTitle: "相機掃描不可用",
    cameraUnsupportedBody: "相機掃描不可用。你仍可用以下方式簽到。",
    cameraUnsupportedHint: "你仍可用以下方式簽到。",
    fallbackTitle: "其他簽到方式",
    fallbackLead: "你已停止掃描。請選擇其他方式完成簽到。",
    manualCodeLabel: "六位數代碼",
    manualCodePlaceholder: "例如 482913",
    manualCodeHint: "輸入現場顯示的六位數代碼。",
    continue: "繼續",
    invalidEntryCode: "找不到此代碼對應的聚會，請確認後重試。",
    offlineResolve: "現時沒有網絡，未能核實聚會資料。請重新連線後再試一次。",
    manualMethodTitle: "輸入代碼",
    manualMethodHint: "輸入現場顯示的六位數代碼。",
    memberQrTitle: "出示會員 QR",
    memberQrHint: "開啟帳戶，出示你的會員 QR 碼。",
    assistedOpen: "開協助簽到",
    cameraUnavailableTitle: "未能使用相機",
    cameraUnavailableHint:
      "你可以檢查瀏覽器權限，或改用下面的聚會代碼繼續 — 兩種方式同樣可靠。",
    manualEntryTitle: "輸入聚會代碼",
    manualEntryHint: "相機不可用時，輸入現場顯示的六位數代碼。",
    manualOnlyTitle: "只在你按下後使用相機",
    manualOnlyHint: "相機權限只會在開始掃描時請求。",
    scanMethodTitle: "簽到方式",
    startScan: "開始掃描",
    scanTitle: "聚會簽到",
    scanLead: "掃描場地顯示的二維碼。",
    invalidManualCode: "請輸入六位數聚會代碼。",
    chooseMeeting: "選擇要簽到的聚會",
    chooseMeetingHint: "此二維碼可用於多個聚會，請揀選你參加的那一個。",
    recognizedMultiple: "已辨識多個聚會",
    rescan: "重新掃描",
    outcomeHeader: "簽到狀態",
    outcomeWindowTitle: "簽到尚未開放",
    outcomeWindowBodyPrefix: "此聚會的簽到時段將於",
    outcomeWindowBodySuffix:
      "開始（聚會開始前 30 分鐘）。開放後可以重新掃描或輸入代碼簽到。",
    outcomeWindowBodySuffixWithoutOffset:
      "開始。開放後可以重新掃描或輸入代碼簽到。",
    outcomeCancelledTitle: "此聚會已取消",
    outcomeCancelledBody:
      "請留意教會通知，或聯絡負責同工了解最新安排。此聚會不會記錄出席。",
    outcomeNotEnrolledTitle: "你尚未報名此課程",
    outcomeNotEnrolledBody:
      "請先查看課程詳情並提交報名，或聯絡負責同工協助登記，之後即可掃描簽到。",
    viewProgramDetail: "查看課程詳情",
    backToScan: "返回掃描",
    // Check-in confirmation + result screens (Spec 085 US 35-40, ticket
    // 085-06 #313): the explicit pre-commit confirmation and the
    // success/duplicate/failure/offline outcomes, exactly as the canonical
    // participant prototype renders them.
    confirmHeader: "確認簽到",
    recognizedBadge: "已辨識",
    confirmTitle: "確認聚會",
    confirmLead: "請核對聚會資料，確認後才會記錄出席。",
    confirmSubmit: "確認簽到",
    notThisEvent: "不是這個聚會",
    resultTitle: "簽到結果",
    successTitle: "簽到完成",
    duplicateTitle: "已完成簽到",
    duplicateBody: "你已在此聚會簽到，無需重複。",
    backHome: "返回首頁",
    scanAgain: "再次簽到",
    submitFailure: "未能完成簽到，請重試一次。",
    offlineSubmit: "未能提交簽到。請重新連線後再次確認；系統不會自動重試。",
    status: {
      Active: "有效",
      Voided: "已作廢",
    },
    method: {
      self_qr_scan: "成員掃描 QR",
      self_manual_code: "成員手動代碼",
      leader_qr_scan: "負責人掃描 QR",
      leader_manual_search: "負責人手動搜尋",
      guest_qr_scan: "訪客掃描 QR",
      guest_manual_code: "訪客手動代碼",
    },
    sheetMethod: "簽到方法",
    sheetScanInstruction: "請使用手機相機掃描 QR 碼以簽到",
    sheetManualCode: "聚會手動代碼",
  },
  profile: {
    title: "我的帳戶",
    subtitle: "出示會員身份，或查看帳戶資料。",
    name: "姓名",
    username: "登入名稱",
    phone: "電話",
    role: "身份",
    status: "狀態",
    statusValid: "會員身份有效",
    qrBadge: "會員二維碼 · 預覽",
    qrCode: "會員二維碼 · 預覽",
    qrSample: "會員二維碼\n（示範樣式）",
    qrEmpty: "目前沒有 QR 資料。",
    qrEmptyHint: "請聯絡教會同工確認帳戶二維碼資料。",
    accountDetails: "帳戶資料",
    settingsTitle: "設定",
    settingsEntry: "設定",
    settingsEntryHint: "帳戶及系統設定",
    accountSettings: "帳戶設定",
    accountSettingsSubtitle: "更改登入名稱或密碼",
    accountSettingsHint: "更改登入名稱或密碼",
    logout: "登出",
  },
  restore: {
    loading: "正在還原工作階段…",
    restored: "工作階段已還原。",
    expired: "工作階段已過期，請重新登入。",
  },
  logout: {
    submit: "登出",
    error: "登出時發生錯誤，但已安全終止工作階段。",
    failedNotice: "登出請求失敗，但本機工作階段已清除。",
    success: "已登出。",
    forbiddenAction: "登出並返回登入",
  },
  account: {
    updatedNotice: "帳戶資料已更新，請重新登入。",
  },
  offlineBanner: "現時沒有網絡。你仍可查看已載入內容；提交前請重新連線。",
  home: {
    greeting: "早晨",
    churchName: "播道會顯恩堂",
    messageReadMore: "閱讀全文 ›",
    subtitle: "下一項與你有關的安排。",
    loading: "正在載入首頁…",
    loadError: "首頁暫時無法載入。",
    retry: "重試載入首頁",
    emptyTitle: "暫時沒有與你有關的聚會",
    emptySubtitle: "你未有已報名的聚會。探索課程，尋找合適的參加機會。",
    explorePrograms: "探索課程",
    churchNews: "教會消息",
    explore: "探索",
    allPrograms: "全部課程",
    viewEvent: "查看聚會",
    enrolledBadge: "已報名",
    announcementTitle: "本週崇拜及聚會安排",
    announcementDate: "8月15日",
    announcementSummary:
      "請留意本週三晚聚會改於二樓禮堂舉行。其他聚會時間維持不變。",
    venueTitle: "到達場地",
    venueInstructions:
      "請按現場指示前往聚會地點，禮堂入口設有接待同工協助登記。如需輪椅通道或其他協助，請提前聯絡教會辦公室。",
    worshipLocation: "崇拜及主要聚會：二樓禮堂",
    familyRoom: "親子室：一樓副堂旁",
    visitorReception: "訪客接待：正門大堂",
    externalLink: "聚會場地資料 · 外部連結",
    externalLinkLabel: "外部連結",
    backHome: "首頁",
    viewAllMessages: "查看全部",
    messagesLead: "崇拜、聚會安排及教會公告。",
    messagesEmpty: "暫時沒有教會消息",
    messagesEmptyHint: "有新公告時會在這裡顯示。",
    messagesListLabel: "教會消息清單",
    messagesNotFound: "找不到此內容。",
    messagesBack: "返回教會消息",
    messagesLoadError: "未能載入教會消息。",
    messagesRetry: "重試載入教會消息",
    messagesLoading: "正在載入教會消息…",
    nextProgramFallback: "門徒訓練基礎課",
    nextEventFallback: "第三課聚會",
    featuredProgramFallback: "慕道入門課程",
    featuredProgramFallbackSub: "現正接受報名 · 9月7日開始",
  },
  sections: {
    home: "首頁",
    profile: "帳戶",
    programs: "課程與活動",
    events: "聚會管理",
    scanner: "掃描",
    notices: "通知",
    management: "管理",
    permissions: "權限管理",
    permissionsHeading: "權限與角色管理",
    placeholder: "內容建置中。",
  },
  notices: {
    noticesTitle: "通知",
    noticesLead: "最新消息與報名狀態。",
    noticesLoading: "正在載入通知…",
    noticesEmpty: "暫時沒有通知",
    noticesEmptyHint: "有新消息時會在這裡顯示。",
    noticesMarkAllRead: "全部標示已讀",
    noticesMarkedAllRead: "已將全部通知標示為已讀",
    noticesMarkAllReadError: "未能更新已讀狀態。請重新連線後再試。",
    noticesUnread: "未讀",
    noticesListLabel: "通知清單",
    noticesRetry: "重試載入通知",
    noticesLoadError: "未能載入通知。",
  },
  // Management Hub directory copy (Spec 087 US 1-3, 22). The group/row
  // labels are the single source for the server-side hub projection
  // (`/api/v1/programs/hub`) and the client renders exactly what the
  // server returns — never a client-side capability branch.
  management: {
    managementTitle: "管理工作",
    managementLead: "在你獲授權的範圍內處理會員、課程、聚會及內容工作。",
    groupMemberPermissions: "會員與權限",
    groupOperations: "事工營運",
    groupContentSystem: "內容與系統",
    approvalsRow: "註冊審批",
    approvalsRowHint: "核准或拒絕會員申請",
    accountsRow: "帳戶名錄",
    accountsRowHint: "搜尋登入身份及帳戶狀態",
    permissionsRow: "帳戶與權限",
    permissionsRowHint: "管理員帳戶及角色",
    departmentsRow: "部門設定",
    departmentsRowHint: "部門開關、管理者及建立課程",
    attendanceRow: "聚會／出席",
    attendanceRowHint: "出席點名、代簽及修正",
    membersRow: "參與者",
    membersRowHint: "搜尋並查看會員資料",
    homeContentRow: "首頁內容",
    homeContentRowHint: "版面 A／B 編輯及發佈",
    anotherEntry: "另一個工作入口",
    goCourseManagement: "前往課程管理",
    goCourseManagementHint:
      "課程 tab 內以管理模式選擇課程，再進入 Course Cockpit。",
    emptyTitle: "目前沒有可用的管理工作",
    loading: "載入中…",
    loadError: "管理工作暫時無法載入，請稍後再試。",
    forbidden: "您沒有權限執行此操作。",
    retry: "重試連接",
    backHome: "返回首頁",
  },
  // Registration Approvals — queue + routable detail (Spec 087 US 4-8,
  // ticket 087-02 #319). The detail is a deep-linkable sub-route of the hub's
  // canonical `/management?module=approvals&request=<id>`; decided requests
  // stay viewable read-only at the same URL. approve/reject/decisionNote/
  // decisionMade intentionally mirror `programs.*` (same UI vocabulary);
  // kept here so the approvals surface has one self-contained source.
  approvals: {
    approvalsTitle: "註冊審批",
    approvalsLead: "核准後會建立帳戶，申請人即可登入。",
    openDetail: "查看申請詳情",
    approvalDetailTitle: "註冊審批 · 詳情",
    backToApprovals: "返回註冊審批",
    applicantName: "姓名",
    applicantContact: "聯絡",
    status: "狀態",
    statusPending: "待審批",
    statusApproved: "已核准",
    statusRejected: "已拒絕",
    approve: "核准",
    approving: "核准中…",
    reject: "拒絕",
    rejecting: "拒絕中…",
    decisionNote: "決定備註",
    decisionNotePlaceholder: "請輸入拒絕原因（必須填寫）",
    rejectionNoteRequired: "拒絕時必須填寫決定備註。",
    decisionMade: "已處理申請。",
    loading: "載入中…",
  },
  // Identity management and permission-editor copy. The Worker supplies the
  // effective identity projection; this block owns labels and state copy only.
  permissions: {
    permissionsTitle: "權限管理",
    permissionsLead: "選擇一個身份組，查看及編輯其有效權限。",
    accountsSection: "管理員帳戶",
    rolesSection: "身份組列表",
    accountName: "姓名",
    accountRole: "角色",
    accountDepartment: "部門",
    roleAdmin: "管理員",
    roleAdminScope: "全部範圍",
    roleStaff: "同工",
    roleStaffScope: "部門範圍內協助工作",
    stateAssigned: "已設",
    stateAssignable: "可指派",
    backToSettings: "設定",
    loading: "載入中…",
    loadError: "身份組資料暫時無法載入，請稍後再試。",
    retry: "重試連接",
    forbidden: "您沒有權限執行此操作。",
    policyTitle: "權限政策",
    policyLead: "按工作範圍核對每個角色可以使用的能力。",
    policySummary: "變更摘要",
    policySynced: "目前顯示政策版本",
    policyAdminEditable: "管理員可編輯未鎖定的政策格。",
    policyStaffReadOnly: "同工只可查看，不能修改權限政策。",
    policyReadOnlyNotice:
      "固定政策格不可修改；管理員可先建立草稿，再一次儲存。",
    policyEnabled: "已啟用",
    policyDisabled: "未啟用",
    policyLocked: "固定",
    policyReadOnly: "只讀",
    policyEditable: "可編輯",
    policyRoleMember: "會友",
    policyDraftTitle: "政策變更草稿",
    policyChangesTitle: "今次變更",
    policyChangeEnabled: "啟用",
    policyChangeDisabled: "停用",
    policyDirty: "有未儲存變更",
    policyDirtyHint: "儲存時會以一個原子變更集更新政策。",
    policySyncedTitle: "政策已同步",
    policySyncedHint: "目前顯示的是最新政策版本。",
    policySave: "儲存變更",
    policySaving: "儲存權限政策…",
    policySaved: "權限政策已儲存",
    policySavedHint: "最新政策已生效，管理畫面會使用新設定。",
    policySaveError: "未能儲存權限政策",
    policySaveErrorHint: "系統沒有套用任何部分變更；你的草稿仍保留在此頁。",
    policyConflict: "權限政策已有更新",
    policyConflictHint: "另一位管理員已儲存較新版本。系統沒有覆蓋你的草稿。",
    policyConflictRevision: "最新政策版本",
    policyReload: "重新載入政策",
    policyReloadHint: "重新載入後可按需要重新套用你的變更。",
    policyPending: "待儲存",
    policyNoChanges: "沒有可儲存的變更。",
  },
  // Member Directory (Spec 087 US 13-15 / ticket 087-04 #321). Church-wide
  // search for Admin/Staff, department-scoped for Department Managers, with
  // the member detail (contact, role, department memberships) rendered inline
  // from a selected result — no separate commit step. Copy is verbatim from
  // the canonical prototype's member-directory and participant-detail screens.
  managementMembers: {
    membersTitle: "參與者",
    membersLead: "搜尋並查看會員資料。",
    searchLabel: "搜尋會員",
    searchPlaceholder: "搜尋會員姓名、登入名稱或電話",
    noResults: "找不到符合的會員",
    emptyHint: "請嘗試其他姓名、登入名稱或電話。",
    memberDetail: "參與者資料",
    memberContact: "聯絡",
    memberRole: "角色",
    memberDepartments: "部門",
    detailUsername: "登入名稱",
    detailPhone: "電話",
    detailStatus: "狀態",
    detailUnavailable: "未提供",
    noDepartments: "未加入任何部門",
    backToManagement: "返回管理工作",
    loading: "載入中…",
    loadError: "暫時無法搜尋會員，請稍後再試。",
    forbidden: "您沒有權限執行此操作。",
    retry: "重試連接",
  },
  accountDirectory: {
    title: "帳戶名錄",
    lead: "搜尋登入身份，核對角色、狀態與部門關聯。",
    searchLabel: "搜尋帳戶",
    searchPlaceholder: "姓名、登入名稱或電話",
    departmentLabel: "部門",
    departmentPlaceholder: "部門名稱（可選）",
    roleLabel: "角色",
    statusLabel: "狀態",
    allRoles: "全部角色",
    allStatuses: "全部狀態",
    admin: "管理員",
    staff: "同工",
    member: "會友",
    pending: "待審批",
    active: "生效",
    suspended: "暫停",
    deactivated: "已停用",
    total: "符合帳戶",
    elevated: "同工及管理員",
    activeCount: "生效帳戶",
    pendingCount: "待處理申請",
    resultsTitle: "帳戶結果",
    noResults: "找不到符合的帳戶",
    emptyHint: "請嘗試其他姓名、登入名稱或電話。",
    detail: "帳戶詳情",
    detailReadOnly: "帳戶停用、角色變更及憑證重設會由另一個決策流程定義。",
    contact: "電話",
    username: "登入名稱",
    role: "角色",
    status: "狀態",
    departments: "部門關聯",
    noDepartments: "未加入任何部門",
    unavailable: "未提供",
    back: "返回管理工作",
    loading: "正在載入帳戶名錄…",
    loadError: "帳戶名錄暫時無法載入，請稍後再試。",
    forbidden: "您沒有權限查看帳戶名錄。",
    retry: "重試連接",
  },
  // Home Content CMS editor (Spec 087 US 16-21 / ticket 087-05 #322).
  // The editor stays a single page: template switching, draft/publish,
  // preview, conflict recovery, and the visible publish audit all share this
  // vocabulary.
  homeEditor: {
    editorTitle: "首頁內容",
    templateA: "版面 A",
    templateB: "版面 B",
    switchTemplate: "切換版面",
    draft: "草稿",
    publish: "發佈",
    publishImmediate: "立即發佈",
    publishScheduled: "預約發佈",
    previewPhone: "手機預覽",
    previewDesktop: "桌面預覽",
    saveDraft: "儲存草稿",
    savePublished: "儲存並發佈",
    conflictTitle: "內容已更新",
    conflictReload: "重新載入最新版本",
    auditTrail: "發佈紀錄",
    auditPublishedBy: "發佈者",
    auditAt: "發佈時間",
    fallbackNote: "如指定聚會不符合條件，首頁會自動顯示下一項合資格聚會。",
    featuredEvent: "精選聚會",
    templateADescription:
      "顯示指定聚會，若不符合條件則自動顯示下一項合資格聚會。",
    fallbackDescription: "下一項合資格聚會會自動顯示。",
    title: "標題",
    summary: "摘要",
    body: "內容",
    ctaLabel: "按鈕文字",
    ctaUrl: "按鈕連結",
    imageUrl: "圖片連結",
    imageAlt: "圖片替代文字",
    preview: "預覽",
    previewLead: "發佈前查看首頁顯示效果。",
    saveSuccess: "草稿已儲存。",
    publishSuccess: "首頁內容已發佈。",
    scheduleStart: "開始時間",
    scheduleEnd: "結束時間",
    statusDraft: "草稿",
    statusPublished: "已發佈",
    scheduledAt: "預約時間",
    updatedAt: "更新時間",
    loading: "載入中…",
    loadError: "首頁內容暫時無法載入，請稍後再試。",
    forbidden: "您沒有權限編輯首頁內容。",
    retry: "重試連接",
    noAudit: "尚未有發佈紀錄。",
  },
  // System Settings hub (Spec 084 US 24-26 / ticket 084-04). Exactly three
  // rows in the locked order; the 簽到設定 and 時區 destinations are pure
  // read-only informational screens — no editable fields anywhere (regression
  // asserted per screen). The 帳戶與權限 row links to the 087-03 permissions
  // matrix at /management?module=permissions.
  settings: {
    settingsTitle: "設定",
    settingsBack: "返回管理工作",
    settingsBackToHub: "設定",
    accountsPermissionsRow: "帳戶與權限",
    accountsPermissionsRowHint: "管理帳戶及授權",
    checkinSettingsRow: "簽到設定",
    checkinSettingsRowHint: "簽到時段及方式",
    timezoneRow: "時區",
    timezoneRowHint: "香港時間（GMT+8）",
    checkinTitle: "簽到設定",
    checkinMethods: "簽到方式",
    memberQr: "會員二維碼",
    memberQrHint: "掃描會員帳戶頁面的二維碼",
    eventCode: "聚會代碼",
    eventCodeHint: "輸入場地顯示的六位數代碼",
    assisted: "代為簽到",
    assistedHint: "同工於出席名單代簽",
    enabledBadge: "已啟用",
    openWindow: "開放時段",
    beforeStart: "聚會開始前",
    beforeStartHint: "開放簽到的提前時數",
    beforeStartValue: "30 分鐘",
    afterEnd: "聚會結束後",
    afterEndHint: "結束後仍可簽到多久",
    afterEndValue: "15 分鐘",
    timezoneTitle: "時區",
    timezoneLead: "聚會、報名及發佈時間均以香港時間顯示。",
    gmt8: "香港時間（GMT+8）",
    gmt8Value: "GMT+8",
  },
  nav: {
    backToHome: "返回首頁",
    backToProfile: "帳戶",
    backToAccount: "帳戶",
    loading: "載入中…",
    unauthorized: "您沒有權限存取此頁面。",
    unknownRoute: "找不到此頁面。",
    label: "主要導航",
  },
  attention: {
    title: "注意事項",
    tabsLabel: "注意事項分類",
    pendingTab: "待處理",
    noticesTab: "通知",
    close: "關閉",
    bellLabel: (count: number) => `開啟注意事項，${count} 項`,
    badgeCount: (count: number) => `目前有 ${count} 項注意事項`,
    pendingEmptyTitle: "目前沒有待處理事項",
    pendingEmptyHint: "需要你處理的事項會在這裡顯示。",
    noticesEmptyTitle: "目前沒有新通知",
    noticesEmptyHint: "有新通知時會在這裡顯示。",
  },
  notAvailable: {
    title: "找不到此內容",
    message: "此頁面不存在，或已不再適用於你的帳戶範圍。請返回首頁重新開始。",
    backToHome: "返回首頁",
  },
  error: {
    networkError: "無法連接伺服器，請檢查網路後再試。",
    unavailable: "系統暫時無法使用，請稍後再試。",
    serverError: "伺服器發生錯誤，請稍後再試。",
    forbidden: "您沒有權限執行此操作。",
    validation: "輸入資料無效，請檢查後再試。",
    notFound: "找不到請求的資料。",
    conflict: "資料衝突，請重新整理後再試。",
    malformed: "伺服器回應格式錯誤。",
    unknown: "發生未知錯誤。",
    retry: "重試連接",
  },
  empty: {
    courseData: "目前沒有課程資料。",
    title: "無資料",
  },
  programs: {
    pageTitle: "課程",
    lead: "先選部門，再處理課程、聚會或報名。",
    entryLead: "尋找合適的課程，查看聚會及報名狀態。",
    participantMode: "參與者模式",
    managementMode: "管理模式",
    managementLead: "只顯示你目前獲授權範圍內的管理入口。",
    modeLabel: "課程模式",
    enterManagement: "進入管理模式",
    enterParticipant: "返回參與者模式",
    backToEntry: "返回課程入口",
    accessLoading: "正在確認管理權限…",
    managementScopeReady: "你的管理範圍已確認。",
    managementBoundaryHint:
      "目前只確認你的管理範圍；實際管理操作會在管理工作區提供。",
    managementDirectoryTitle: "管理課程目錄",
    managementDirectoryLead:
      "只列出你目前可操作的課程；你可以按課程名稱、類別或部門搜尋。",
    managementDirectorySearchLabel: "搜尋可管理課程",
    managementDirectorySearchPlaceholder: "搜尋課程名稱、簡介、類別或部門",
    managementDirectoryClearSearch: "清除搜尋",
    managementDirectoryListLabel: "可管理課程",
    managementDirectoryLoading: "正在載入管理課程目錄…",
    managementDirectoryLoadError: "無法載入管理課程目錄",
    managementDirectoryForbidden: "無法載入管理課程目錄",
    managementDirectoryForbiddenHint: "你的管理範圍可能已變更，請重新確認。",
    managementDirectoryRetry: "重試載入管理課程目錄",
    managementDirectoryEmpty: "目前沒有可管理的課程",
    managementDirectoryEmptyHint: "獲授權的課程會在這裡顯示。",
    managementDirectoryNoMatches: "找不到符合的可管理課程",
    managementDirectoryNoMatchesHint: "請清除搜尋，或嘗試其他關鍵字。",
    managementScopeDepartment: "部門範圍",
    managementScopeProgram: "指定課程",
    cockpitNextMeeting: "下一聚會",
    cockpitOperations: "營運",
    cockpitWeeklyWork: "每週工作",
    cockpitEventsTile: "聚會",
    cockpitParticipantsTile: "參與者",
    cockpitEventsCount: "{count} 個聚會",
    cockpitPendingLabel: "待審批報名 ×{count}",
    cockpitNoPending: "查看活躍名單",
    cockpitOthers: "其他",
    cockpitLowFrequency: "低頻設定",
    cockpitCourseFacts: "課程資料",
    cockpitCourseFactsHint: "只讀摘要與分類標籤",
    cockpitSettings: "設定",
    cockpitManageRoster: "前往管理名單",
    cockpitCheckedIn: "已簽到",
    cockpitAutoScheduled: "自動排程",
    cockpitEditProgram: "編輯課程",
    cockpitEmptyScopeTitle: "沒有可管理的課程",
    cockpitEmptyScopeHint: "你的帳戶目前未獲分配任何部門或課程的管理權限。",
    courseFacts: "課程資料",
    courseFactsHint: "只讀摘要與分類標籤",
    courseFactsNote: "課程資料是只讀摘要；編輯時會重新驗證目前管理範圍。",
    factsName: "課程名稱",
    factsDepartment: "所屬部門",
    factsPurpose: "課程簡介",
    factsLifecycle: "課程狀態",
    factsDiscoverability: "可見性",
    factsEnrollmentMode: "報名方式",
    editTitle: "編輯課程",
    editNameLabel: "課程名稱",
    editPurposeLabel: "課程簡介",
    saveCourse: "儲存課程",
    courseSaved: "課程已更新",
    editRequired: "請完成課程名稱及簡介",
    workspaceTitle: "課程工作區",
    workspaceLead: "先確認課程狀態，再進入一項明確的管理工作。",
    workspaceBack: "返回管理課程目錄",
    workspaceLoading: "正在載入課程工作區…",
    workspaceLoadError: "無法載入課程工作區",
    workspaceForbidden: "無法進入課程工作區",
    workspaceUnavailable: "課程管理範圍已失效",
    workspaceUnavailableHint:
      "這個課程目前不可用，或你的管理範圍已被撤回。請返回管理課程目錄。",
    workspaceRetry: "重試載入課程工作區",
    workspaceSummaryLoading: "正在載入工作區摘要…",
    workspaceSummaryUnavailable: "摘要資料暫時不可用。",
    workspaceIdentity: "課程資料",
    workspaceDescription: "簡介",
    workspaceCategory: "類別",
    workspaceDepartment: "所屬部門",
    workspaceBehavior: "形式",
    workspaceLifecycle: "狀態",
    workspaceDiscoverability: "可見性",
    workspaceEnrollmentMode: "報名方式",
    workspaceNearestEvent: "最近聚會",
    workspaceNearestEventNone: "目前沒有可用的聚會資料。",
    workspaceAttention: "需要留意",
    workspacePendingRequests: "待處理報名",
    workspaceActiveParticipants: "活躍參與者",
    workspaceInactiveEvents: "暫停中的聚會",
    workspaceCancelledEvents: "已取消聚會（供檢視）",
    workspaceNoAttention: "目前沒有待處理項目。",
    attentionControlLabel: "管理提示",
    attentionTitle: "管理提示",
    attentionCount: "{count} 項可處理提示",
    attentionLoading: "正在載入管理提示…",
    attentionRetry: "重試載入提示",
    attentionZero: "目前沒有需要處理或檢視的項目。",
    attentionListLabel: "管理提示清單",
    attentionViewAll: "查看全部管理提示",
    attentionEnrollmentLabel: "待處理報名",
    attentionEventCount: "{count} 場聚會需檢視",
    attentionCancelledCount: "{count} 場聚會狀態",
    attentionEnrollmentCount: "{count} 項申請",
    attentionEnrollmentBadge: "待處理報名 {count} 項",
    attentionEventBadge: "暫停聚會 {count} 場",
    attentionCancelledBadge: "已取消聚會 {count} 場",
    attentionEventLabel: "聚會需檢視",
    attentionEventInformationalLabel: "聚會狀態",
    notificationBellLabel: "管理通知",
    notificationBellTitle: "開啟管理通知",
    notificationsTitle: "管理通知",
    notificationsLead: "只顯示目前管理範圍內仍需留意的最新狀態。",
    notificationsLoading: "正在載入管理通知…",
    notificationsEmpty: "目前沒有新的管理通知。",
    notificationsListLabel: "管理通知清單",
    notificationsRetry: "重試載入通知",
    notificationsReadError: "通知狀態未能更新，請重試。",
    notificationsViewAll: "查看全部通知",
    notificationsCount: "{count} 項未讀通知",
    notificationsUnread: "未讀",
    notificationsEnrollmentLabel: "待處理報名",
    notificationsEnrollmentCount: "{count} 項申請",
    notificationsEventLabel: "聚會需要處理",
    notificationsEventInformationalLabel: "聚會狀態更新",
    workspaceTaskLabel: "管理工作",
    workspaceTaskEvents: "聚會",
    workspaceTaskParticipants: "參與者",
    workspaceTaskSettings: "課程設定",
    workspaceTaskNotifications: "管理通知",
    workspaceTaskEventsLead:
      "查看這個課程的聚會記錄；建立聚會並於聚會詳情中編輯。",
    workspaceTaskParticipantsLead:
      "查看報名申請與活躍參與者；決定與新增操作由參與者工作流程處理。",
    workspaceTaskSettingsLead:
      "集中管理這個課程本身的基本資料、報名、時間表與出席預設。",
    settingsBasics: "基本資料",
    settingsBasicsLead: "更新課程名稱、簡介、類別及在課程目錄中的顯示次序。",
    settingsEnrollment: "報名與可見性",
    settingsEnrollmentLead:
      "這些設定會影響日後的課程發現和報名方式，不會改寫既有報名紀錄。",
    settingsSchedule: "時間表",
    settingsScheduleLead:
      "只設定定期課程的重複規則；產生具體聚會請到聚會工作流程。",
    settingsAttendance: "出席",
    settingsAttendanceLead:
      "這是課程層級的簽到預設，具體聚會會按這些相對時間計算簽到時段。",
    settingsNoManagement: "目前沒有課程設定管理能力。",
    settingsNoManagementHint:
      "你的管理範圍仍然保留，但這個課程的設定不能由目前帳戶編輯。",
    settingsSaved: "課程設定已儲存。",
    settingsSaveBasics: "儲存基本資料",
    settingsSaveEnrollment: "儲存報名與可見性",
    settingsSaveAttendance: "儲存出席預設",
    settingsBasicsValidation: "請填寫課程名稱，並輸入不小於零的整數顯示次序。",
    settingsAttendanceValidation: "請輸入不小於零的整數分鐘。",
    settingsConfirmEnrollment:
      "確認後會影響日後的新報名與課程目錄顯示；既有紀錄不會改變。",
    settingsConfirmChange: "確認變更",
    settingsKeepCurrent: "保留目前設定",
    settingsLifecycle: "生命週期",
    settingsLifecycleHint:
      "生命週期轉換由課程管理流程處理；請返回概覽使用現有的啟用或存檔操作。",
    settingsScheduleOneOff:
      "單次課程不使用固定時間表。請到聚會工作流程建立或管理具體聚會。",
    settingsScheduleUnavailable:
      "所屬部門目前未啟用聚會模組；不能在這裡編輯時間表規則。",
    settingsAttendanceUnavailable:
      "所屬部門目前未啟用出席模組；不能在這裡編輯簽到預設。",
    settingsExceptionsLoadError: "無法載入既有例外安排，請重試時間表。",
    settingsExistingExceptions: "既有例外安排",
    settingsScheduleLoading: "正在載入時間表規則…",
    settingsScheduleLoadError: "無法載入時間表規則。",
    settingsScheduleRetry: "重試載入時間表",
    settingsScheduleNone: "目前尚未設定時間表規則。",
    settingsRuleEdit: "編輯規則",
    settingsRuleCancel: "取消編輯",
    settingsRuleSave: "儲存規則",
    settingsRuleAddException: "新增例外",
    settingsExceptionDate: "例外日期",
    settingsExceptionAction: "例外處理",
    settingsExceptionCancel: "取消該次",
    settingsExceptionReschedule: "改期該次",
    settingsExceptionNewStart: "新開始時間",
    settingsExceptionNewEnd: "新結束時間",
    settingsExceptionSave: "儲存例外",
    settingsExceptionRestore: "移除例外",
    settingsExceptionDateValidation: "請選擇有效的例外日期。",
    settingsExceptionDuplicate: "此日期已有例外安排，無法重複新增。",
    settingsScheduleEventsLink: "前往聚會工作流程",
    settingsAttendanceOpens: "開始前可簽到分鐘",
    settingsAttendanceCloses: "結束後仍可簽到分鐘",
    settingsAttendanceUnits: "分鐘",
    workspaceTaskEventsLoading: "正在載入聚會…",
    workspaceTaskEventsError: "無法載入聚會",
    workspaceTaskEventsRetry: "重試載入聚會",
    workspaceTaskEventsEmpty: "目前沒有聚會。",
    workspaceTaskParticipantsLoading: "正在載入參與者資料…",
    workspaceTaskParticipantsError: "無法載入參與者資料",
    workspaceTaskParticipantsRetry: "重試載入參與者資料",
    workspaceTaskParticipantsEmpty: "目前沒有報名或活躍參與者。",
    workspaceParticipantsRefresh: "重新整理參與者資料",
    workspaceParticipantsRefreshSuccess: "參與者資料已更新。",
    workspaceParticipantsRefreshFailed:
      "更新參與者資料失敗，畫面顯示上次已知結果。",
    workspaceParticipantsForbidden: "你目前無法操作這個課程的參與者資料。",
    workspaceParticipantsStale: "這項報名資料已過時，請重新整理後再試。",
    workspaceParticipantsConflict: "這項操作與另一項更新衝突，資料未有改變。",
    workspaceParticipantsPendingEmpty: "目前沒有待處理報名。",
    workspaceParticipantsActiveEmpty: "目前沒有活躍參與者。",
    workspaceParticipantsHistoryEmpty: "目前沒有歷史或撤回紀錄。",
    workspaceTaskSettingsCapabilities: "目前能力",
    workspaceTaskSettingsNoCapabilities: "目前沒有可用的課程管理能力。",
    workspaceTaskUnavailable: "這項工作目前未在所屬部門啟用。",
    workspaceCapabilityManage: "課程管理",
    workspaceCapabilityPublish: "發佈課程",
    workspaceCapabilityLeaderAssign: "委派負責人",
    noManagementScope: "沒有管理範圍",
    noManagementScopeHint: "目前沒有可用的課程管理範圍。",
    managementForbidden: "無法進入管理模式",
    managementForbiddenHint: "你沒有權限進入這個管理範圍。",
    malformedIntent: "連結資料無效",
    malformedIntentHint: "請返回課程入口，再開啟有效的活動連結。",
    directProgramIntent: "已保留活動連結",
    directProgramIntentHint: "活動內容會在課程任務中開啟；目前先保留你的連結。",
    detailBack: "課程",
    detailLoading: "正在載入課程內容…",
    detailLoadError: "無法載入課程內容",
    detailRetry: "重試載入課程內容",
    detailUnavailable: "無法開啟這個課程",
    detailUnavailableHint:
      "這個課程目前不可用，或你未有權限查看。請返回課程目錄。",
    detailPurpose: "課程簡介",
    nextMeeting: "下一次聚會",
    sessionFallback: "第 {n} 課聚會",
    detailEventLocation: "地點",
    viewEventDetail: "查看聚會詳情",
    scheduleTitle: "聚會時間表",
    scheduleExpandAll: "顯示全部 {count} 節 ↓",
    eventFallbackTitle: "{name} 聚會",
    scheduleRulesGroup: "時間規則",
    scheduleEventsGroup: "即將舉行",
    conflictNote: "此時段與「{program}」聚會時間相近，僅供提示，不影響報名。",
    archivedNote: "此課程已封存，暫不接受報名",
    detailBehavior: "形式",
    detailLifecycle: "狀態",
    detailParticipation: "參與方式",
    detailDepartment: "所屬部門",
    detailCategory: "類別",
    detailSchedule: "時間安排",
    detailScheduleNone: "目前未提供固定時間安排。",
    detailEvents: "近期活動",
    detailEventsNone: "目前沒有即將進行的活動。",
    detailEventTime: "活動時間",
    detailBehaviorRecurring: "Recurring · 定期",
    detailBehaviorOneOff: "OneOff · 單次",
    detailLifecycleDraft: "Draft · 草稿",
    detailLifecycleActive: "Active · 啟用",
    detailLifecycleArchived: "Archived · 已存檔",
    detailParticipationMemberRequest: "MemberRequest · 可報名",
    detailParticipationManagerOnly: "ManagerOnly · 僅限負責人",
    scheduleDays: ["日", "一", "二", "三", "四", "五", "六"],
    retryAccess: "重試確認管理權限",
    catalogLoading: "正在載入課程",
    catalogReady: "課程目錄已載入。",
    catalogEmpty: "找不到相關課程",
    catalogEmptyHint: "請嘗試其他關鍵字或清除篩選。",
    catalogNoPrograms: "目前沒有可顯示的課程",
    catalogNoProgramsHint: "如需協助，請聯絡事工負責人。",
    catalogLoadError: "未能載入課程",
    catalogLoadErrorHint: "請檢查網絡後再試。你的搜尋條件會保留。",
    catalogRetry: "重新載入",
    catalogForbidden: "無法載入課程目錄",
    catalogForbiddenHint: "你沒有權限查看課程目錄。",
    catalogSearchLabel: "搜尋課程",
    catalogClearSearch: "清除搜尋",
    catalogNoMatches: "找不到相關課程",
    catalogNoMatchesHint: "請嘗試其他關鍵字或清除篩選。",
    catalogNoFilterMatchesHint: "請嘗試其他關鍵字或清除篩選。",
    catalogClearFilters: "清除搜尋與篩選",
    catalogListLabel: "課程目錄",
    catalogFilterLifecycle: "課程狀態",
    catalogFilterParticipation: "參與方式",
    filterGroupLabel: "課程篩選",
    filterAll: "全部",
    filterEligible: "可報名",
    filterActive: "已參加",
    filterPending: "待審批",
    filterDraft: "草稿",
    filterArchived: "已存檔",
    filterMemberRequest: "可報名",
    filterManagerOnly: "僅限負責人",
    statusActive: "已參加",
    statusPending: "待審批",
    statusEligible: "可報名",
    statusManagerOnly: "由同工安排",
    statusWithdrawn: "已取消申請",
    statusCancelled: "已退出",
    statusRejected: "已拒絕",
    statusArchived: "已封存",
    catalogPendingCopy: "已提交申請 · 待審批",
    catalogManagerOnlyCopy: "為崇拜事奉團隊而設",
    catalogRejectedCopy: "上次申請未獲批准，可重新提交",
    catalogArchivedCopy: "此課程已封存，暫不接受報名",
    catalogActivePrefix: "下一次聚會：",
    catalogEventCountSuffix: "共 {count} 節",
    programUnavailable: "無法開啟這個課程",
    programUnavailableHint:
      "這個課程目前不可用，或你未有權限查看。你可以繼續瀏覽其他課程。",
    programSelected: "已保留課程連結。",
    departments: "部門",
    departmentsTitle: "部門設定",
    departmentsLead: "只顯示你獲授權管理的部門。",
    programs: "課程與活動",
    modules: "模組",
    moduleDisabled: "此功能模組尚未啟用。請先啟用模組，相關功能才會顯示。",
    noDepartments: "目前沒有部門。新增部門後，就可以開始建立課程。",
    noPrograms: "此部門尚未有課程。啟用課程目錄後可新增。",
    createDepartment: "新增部門",
    createProgram: "建立課程",
    createProgramInDepartmentHint:
      "從目前部門建立課程，課程會先以草稿狀態建立。",
    deptCode: "部門代碼",
    deptName: "部門名稱",
    deptCodePlaceholder: "例如：青區",
    deptNamePlaceholder: "部門名稱",
    programName: "課程名稱",
    programNamePlaceholder: "課程名稱",
    programPurpose: "課程目的",
    purposeRequired: "請填寫課程名稱及目的。",
    programDescription: "課程簡介",
    programCategory: "活動類別",
    programLifecycle: "課程狀態",
    programEnrollmentMode: "報名方式",
    programDisplayOrder: "顯示次序",
    programDetails: "查看課程詳情",
    programOverview: "概覽",
    programTasks: "課程工作",
    programEdit: "基本資料",
    programEvents: "聚會與時間表",
    programEnrollment: "報名",
    programLeaders: "事工負責人",
    backToOverview: "返回概覽",
    programDescriptionEmpty: "未填寫課程簡介。",
    editProgram: "編輯課程",
    saveProgram: "儲存課程",
    cancelEdit: "取消編輯",
    programCreateTitle: "建立課程",
    programCreateLead: "選擇獲授權部門，建立定期或單次課程。",
    programEditLead: "更新課程資料；儲存後會重新確認工作區內容。",
    programSaved: "課程已儲存，正在返回工作區。",
    programCreatedNotice: "課程已建立（草稿狀態）",
    programCreateUnavailable: "目前沒有可建立課程的部門。",
    programCreateForbidden: "你沒有在任何部門建立課程的權限。",
    programCategoryRequired: "請填寫活動類別。",
    programCreateDraftOnlyHint:
      "所選部門未獲授權發佈課程；課程會先以草稿建立。",
    programConflict: "課程名稱與現有資料衝突，請重新整理後再試。",
    programTransportAmbiguous:
      "未能確認課程是否已儲存。請重新整理工作區後再試，避免重複提交。",
    archiveBlocked:
      "課程仍有未完成的未來營運承諾，先處理相關聚會或報名後再存檔。",
    archiveAlreadyArchived: "此課程已被其他負責人存檔。",
    archiveProgram: "存檔課程",
    activateProgram: "啟用課程",
    behaviorType: "形式",
    behaviorRecurring: "定期",
    behaviorOneOff: "單次",
    lifecycleDraft: "草稿",
    lifecyclePending: "籌備中",
    lifecycleActive: "啟用",
    lifecycleArchived: "已存檔",
    discoverabilityListed: "公開",
    discoverabilityUnlisted: "不公開",
    moduleProgramCatalog: "課程目錄",
    moduleEnrollment: "報名",
    moduleEvents: "聚會",
    moduleAttendance: "出席",
    moduleCustomForms: "自訂表格",
    departmentSettings: "部門設定",
    departmentDetails: "部門資料",
    saveDepartment: "儲存部門",
    departmentScopeHint: "此設定只適用於目前部門，不會改變其他部門範圍。",
    enable: "啟用",
    disable: "停用",
    expand: "展開",
    collapse: "收合",
    submit: "建立",
    submitting: "建立中…",
    withdrawing: "退出中…",
    cancelRevoke: "取消",
    created: "已建立。",
    updated: "已更新。",
    loadError: "無法載入課程與活動資料，請稍後再試。",
    events: "聚會",
    eventsEmpty: "目前沒有聚會。",
    noRules: "尚未設定時間表。",
    eventDate: "日期",
    eventTime: "時間",
    eventStatus: "狀態",
    eventActive: "進行",
    eventCancelled: "已取消",
    eventScheduleSource: "自動",
    eventManualSource: "手動",
    hkTimeMarker: "時間均以香港時間顯示（GMT+8）。",
    ruleWeekly: "每週",
    ruleMonthly: "每月",
    dayOfWeekLabel: "每週日子",
    weekdaySunday: "星期日",
    weekdayMonday: "星期一",
    weekdayTuesday: "星期二",
    weekdayWednesday: "星期三",
    weekdayThursday: "星期四",
    weekdayFriday: "星期五",
    weekdaySaturday: "星期六",
    monthDayLabel: "每月日子",
    startTime: "開始時間",
    endTime: "結束時間",
    addRule: "新增時間表",
    // EVT-02 (#252): recurring preview and generation.
    ruleLocation: "地點",
    ruleLocationPlaceholder: "輸入地點（可留空）",
    previewEvents: "預覽聚會",
    previewing: "預覽中…",
    previewed: "已預覽 {count} 場聚會。",
    previewRequiresRecurring: "只有定期課程可預覽聚會。",
    previewError: "無法預覽聚會。",
    previewHorizon: "預覽範圍（天數）",
    previewLead: "預覽會依目前時間表產生未來聚會清單，不會寫入任何聚會記錄。",
    previewPlanLabel: "方案 {id}",
    previewPlanMeta: "由 {rules} 條規則組成，範圍 {days} 天（香港時間）。",
    previewOccurrenceDate: "日期",
    previewOccurrenceTime: "時間",
    previewOccurrenceLocation: "地點",
    previewOccurrenceRule: "來源規則",
    previewOccurrenceSkipped: "本次已取消",
    previewOccurrenceDuplicate: "已存在，將略過",
    previewOccurrenceRescheduled: "已改期",
    previewNone: "尚未預覽。請先按「預覽聚會」產生未來聚會清單。",
    previewEmpty: "此範圍內沒有符合時間表的聚會。",
    previewChanged: "時間表已變更，請重新預覽。",
    generateRequiresPreview: "請先預覽時間表再產生聚會。",
    generatedPartial:
      "已產生 {created} 場，跳過 {skipped} 場，{failed} 場失敗。",
    generatedResumed: "已接續上次產生，新增 {created} 場，跳過 {skipped} 場。",
    generateEvents: "產生聚會",
    generating: "產生中…",
    generated: "已產生 {created} 場聚會，跳過 {skipped} 場重複。",
    generateRequiresRecurring: "只有定期課程可產生聚會。",
    createEvent: "新增聚會",
    createMeeting: "建立聚會",
    createMeetingValidation: "請輸入日期、時間及聚會名稱。",
    editMeeting: "編輯聚會",
    eventType: "類型",
    recurrenceTag: "重複標記",
    eventTypeOptions: ["崇拜", "訓練", "小組", "排練", "外展", "其他"],
    recurrenceNone: "無",
    recurrenceWeekly: "每週",
    recurrenceMonthly: "每月",
    repeatLabel: "重複：{tag}",
    repeatInformational: "「重複標記」只作顯示參考，不會自動生成其他聚會。",
    repeatFormInformational: "重複標記僅供顯示參考；不會建立或連結其他聚會。",
    editWithAttendanceNotice: "已有出席記錄，變更已記錄原因與時間",
    cancelBlockedWithAttendance:
      "此聚會已有出席記錄，不能取消；如需更正請使用出席名單的作廢功能。",
    cancelMeetingConfirmTitle: "取消此聚會？",
    cancelMeetingConfirmBody:
      "取消後此聚會不再開放簽到，記錄會保留為「已取消」。",
    confirmCancel: "取消聚會",
    keepMeeting: "保留聚會",
    secondaryGeneratorLabel: "按時間表預覽及產生聚會",
    eventStart: "開始時間（香港時間）",
    eventEnd: "結束時間（香港時間）",
    cancelEvent: "取消聚會",
    cancelEventConfirm: "確定取消這場聚會嗎？取消後仍會保留記錄。",
    confirmCancelEvent: "取消聚會",
    keepEvent: "保留聚會",
    cancelReason: "取消原因",
    cancelReasonPlaceholder: "請填寫取消原因",
    eventCancelledNotice: "聚會已取消。",
    cancelledReason: "取消原因：{reason}",
    eventCancellationBlocked:
      "此聚會已有出席記錄，不能取消；如需更正請使用出席名單的作廢功能。",
    rescheduleEvent: "改期",
    confirmReschedule: "確認改期",
    rescheduleStart: "改期開始時間",
    rescheduleEnd: "改期結束時間",
    cancelOccurrence: "取消該次",
    cancelOccurrenceConfirm: "確定取消這次聚會嗎？之後可以恢復。",
    confirmCancelOccurrence: "確定取消該次",
    keepOccurrence: "保留該次",
    restoreOccurrence: "恢復該次",
    exceptionUpdatedNotice: "已更新例外。",
    exceptionRemovedNotice: "已移除例外。",
    eventRescheduledBadge: "已改期至 {time}",
    eventCancelledBadge: "本次已取消",
    eventsLoadError: "無法載入聚會資料，請稍後再試。",
    ruleCreateError: "無法新增時間表。",
    exceptionCreateError: "無法更新例外。",
    eventCreateError: "無法新增聚會。",
    generateError: "無法產生聚會。",
    enrollment: "報名",
    enrollmentModeMemberRequest: "成員申請",
    enrollmentModeManagerOnly: "管理員安排",
    enroll: "報名",
    reEnroll: "重新報名",
    requestEnroll: "申請報名",
    requestSubmitted: "報名申請已提交",
    withdrawRequest: "取消申請",
    requestWithdrawnNotice: "已取消申請",
    withdrawConfirmTitle: "取消報名申請？",
    withdrawConfirmBody: "你仍可在課程接受報名期間重新提交。",
    withdrawConfirmAccept: "取消申請",
    cancelConfirmTitle: "退出課程？",
    cancelConfirmBody: "退出後如需再參加，需重新報名。",
    cancelConfirmAccept: "退出課程",
    offlineError: "未能儲存。請重新連線後再試。",
    enrollmentOfflineError: "未能提交。請重新連線後再試。",
    requests: "報名申請",
    noRequests: "目前沒有報名申請。",
    tabsPending: "待審批",
    tabsActive: "使用中",
    tabsHistory: "歷史",
    tabsEmpty: {
      pending: "目前沒有待處理報名。",
      active: "目前沒有活躍參與者。",
      history: "目前沒有歷史或撤回紀錄。",
    },
    pendingEmpty: "目前沒有待處理報名。",
    activeEmpty: "目前沒有活躍參與者。",
    historyEmpty: "目前沒有歷史或撤回紀錄。",
    requestPending: "待處理",
    requestApproved: "已核准",
    requestRejected: "已拒絕",
    requestWithdrawn: "已撤回",
    requestSubmittedAt: "申請日期",
    approve: "核准",
    reject: "拒絕",
    decisionNote: "決定備註",
    decisionMade: "已處理申請。",
    enrollments: "報名記錄",
    noEnrollments: "目前沒有報名記錄。",
    enrollmentActive: "已加入",
    enrollmentCancelled: "已取消",
    cancelEnrollment: "退出課程",
    enrollmentCancelledNotice: "已退出課程",
    assistedEnroll: "代報名",
    assistedEnrollAck: "只會建立報名紀錄，不會自動簽到。",
    memberId: "成員 ID",
    memberIdPlaceholder: "輸入姓名或用戶名稱",
    memberSearchHint: "輸入姓名或用戶名稱，從現有會友中選擇。",
    memberSearchLoading: "搜尋會友中…",
    memberSearchError: "暫時無法搜尋會友，請稍後再試。",
    memberSearchRetry: "重試搜尋",
    memberSearchEmpty: "找不到符合的現有會友。",
    memberSearchResults: "找到 {count} 位會友。",
    clearMember: "清除選擇",
    assistedSubmitted: "已新增報名。",
    managerOnlyNote: "此課程由同工安排參加",
    selfEnrollmentNote: "你已加入此課程。",
    enrollmentError: "報名操作失敗。",
    enrollmentHistory: "你的報名紀錄",
    enrollmentScheduleAdvisory:
      "申請前請確認時間是否適合；系統只提供提示，不會因時間重疊自動阻擋。",
    enrollmentEventDetailAdvisory: "加入後可查看聚會詳情",
    enrollmentUnavailableNote: "目前無法在此頁處理你的報名。",
    enrollmentIneligibleNote: "你目前沒有此課程的報名資格。",
    enrollmentDraftNote: "此課程尚未開放報名。",
    enrollmentArchivedNote: "此課程已存檔，不能提交新的報名。",
    enrollmentActiveHint: "你目前已加入此課程。",
    requestPendingHint: "申請已送出，等待課程負責人處理。",
    requestRejectedHint: "上次申請未獲接納；如課程仍開放，可重新申請。",
    requestWithdrawnHint: "你已撤回上次申請；如課程仍開放，可重新申請。",
    enrollmentCancelledHint: "這次報名已取消；如課程仍開放，可重新申請。",
    identityAssignments: "身份組指派",
    noIdentityAssignments: "目前沒有已指派身份組。",
    enrollmentAccountInactive:
      "無法新增報名：此帳戶不存在或尚未啟用。請選取狀態為「啟用」的帳戶。",
    enrollmentDuplicate: "此會友已報名此課程。",
    // EVT-01 (#251): event operational detail and independent availability.
    eventCreate: "新增聚會",
    eventCreateTitle: "聚會資料",
    eventCreateSubmit: "建立聚會",
    eventCreateCancel: "取消建立",
    eventDetailOpen: "詳情",
    eventDetailBack: "返回聚會列表",
    eventDetailTitle: "聚會詳情",
    checkInAvailable: "可簽到",
    checkInInstructionsHeading: "簽到說明",
    eventInstructions: "請於簽到時間內前往掃描，確認聚會後完成簽到。",
    eventInstructionsClosed: "簽到時間尚未開始，屆時可前往掃描完成簽到。",
    goToScan: "前往掃描",
    backToOrigin: "返回",
    eventDetailNotFound: "找不到此聚會。",
    eventDetailLoading: "正在載入聚會詳情…",
    eventDetailRecoveryTitle: "無法開啟這個聚會",
    eventDetailViewProgram: "查看課程詳情",
    eventDetailBackToCatalog: "返回課程目錄",
    eventName: "聚會名稱",
    eventNamePlaceholder: "輸入聚會名稱（可留空）",
    eventLocation: "地點",
    eventLocationPlaceholder: "輸入地點（可留空）",
    eventDetailLeaders: "事工負責人",
    eventDetailParticipantSummary: "報名與出席",
    eventActiveEnrollments: "已報名 {count} 人",
    eventCheckedIn: "已簽到 {count} 人",
    eventNoParticipants: "目前未有報名或簽到記錄。",
    eventAvailability: "開放狀態",
    eventAvailable: "開放",
    eventUnavailable: "暫停",
    eventAvailabilityDeactivate: "暫停聚會",
    eventAvailabilityActivate: "恢復開放",
    eventAvailabilityConfirmTitle: "暫停此聚會？",
    eventAvailabilityConfirmBody:
      "暫停後，此聚會將停止開放簽到（{count} 項進行中的操作會受影響）。",
    eventAvailabilityConfirmProceed: "確定暫停",
    eventAvailabilityNotice: "聚會已暫停開放。",
    eventAvailabilityRestoredNotice: "聚會已恢復開放。",
    eventAvailabilityUndo: "復原",
    eventEditTitle: "編輯聚會資料",
    eventEditSave: "儲存更改",
    eventEditCancel: "取消編輯",
    eventSavedNotice: "聚會資料已更新。",
    eventCreatedNotice: "聚會已建立。",
    eventAvailabilityConfirmRequired:
      "此聚會有進行中的操作，需確認後才能暫停。",
    eventRescheduleBlocked: "此聚會已有出席紀錄，不能更改時間。",
    eventUnavailableCheckIn: "此聚會已暫停開放，不能簽到。",
    eventCheckInWindow: "簽到時間",
    eventCheckInWindowOpensAt: "開放簽到",
    eventCheckInWindowClosesAt: "結束簽到",
  },
} as const;

const ERROR_COPY_BY_CODE: Record<string, string> = {
  CONFLICT: COPY.error.conflict,
  STALE: COPY.programs.workspaceParticipantsStale,
  ENROLLMENT_ACCOUNT_INACTIVE: COPY.programs.enrollmentAccountInactive,
  ENROLLMENT_DUPLICATE: COPY.programs.enrollmentDuplicate,
  EVENT_CANCELLED: COPY.attendance.eventCancelled,
  CHECK_IN_CLOSED: COPY.attendance.eventClosed,
  INVALID_CHECK_IN_ENTRY: COPY.attendance.invalidEntry,
  ENROLLMENT_REQUIRED: COPY.attendance.enrollmentRequired,
  RATE_LIMITED: COPY.attendance.rateLimited,
  DUPLICATE_ATTENDANCE: COPY.attendance.guestDuplicate,
  CONFIRMATION_REQUIRED: COPY.programs.eventAvailabilityConfirmRequired,
  EVENT_RESCHEDULE_BLOCKED: COPY.programs.eventRescheduleBlocked,
  EVENT_CANCEL_BLOCKED: COPY.programs.cancelBlockedWithAttendance,
  STALE_PLAN: COPY.programs.previewChanged,
  PLAN_NOT_FOUND: COPY.programs.previewNone,
  EVENT_UNAVAILABLE: COPY.programs.eventUnavailableCheckIn,
  UNAVAILABLE: COPY.error.unavailable,
  INTERNAL_ERROR: COPY.error.serverError,
  MALFORMED_RESPONSE: COPY.error.malformed,
  MALFORMED_REQUEST: COPY.error.malformed,
};

export function errorCopyFor(
  code?: string,
  // _detail is surfaced only for VALIDATION problems, whose server detail is
  // a specific user-facing Cantonese sentence; PROGRAM_ARCHIVE_BLOCKED uses
  // it as a machine-readable reason discriminator. Every other code keeps
  // centralized copy as the sole user-facing source.
  _detail?: string
): string {
  if (code === "NETWORK_ERROR") {
    return COPY.error.networkError;
  }
  if (code === "AUTH_REQUIRED") {
    return COPY.restore.expired;
  }
  if (code === "FORBIDDEN") {
    return COPY.error.forbidden;
  }
  if (code === "VALIDATION") {
    // Server VALIDATION problems carry a specific, user-facing Cantonese
    // detail (e.g. 請輸入有效電話號碼。); surface it instead of the generic
    // catch-all so the guest/member panels show why the submit was refused.
    // Other codes keep the centralized copy as the sole user-facing source.
    return _detail?.trim() ? _detail : COPY.error.validation;
  }
  if (code === "NOT_FOUND" || (code && code.endsWith("_NOT_FOUND"))) {
    return COPY.error.notFound;
  }
  if (code === "PROGRAM_ARCHIVE_BLOCKED") {
    // 'already_archived' means a different actor reached the terminal state
    // first — not an unresolved-commitment conflict, so it gets its own copy.
    return _detail?.includes("already_archived")
      ? COPY.programs.archiveAlreadyArchived
      : COPY.programs.archiveBlocked;
  }
  return ERROR_COPY_BY_CODE[code ?? ""] ?? COPY.error.unknown;
}

/** Shared error-to-message mapper for program components.
 * RpcError -> errorCopyFor (with detail for VALIDATION/ARCHIVE_BLOCKED);
 * everything else -> generic network error. */
export function errorMessage(error: unknown): string {
  return error instanceof RpcError
    ? errorCopyFor(error.problem.code, error.problem.detail)
    : COPY.error.networkError;
}

// Traditional Chinese landing-page copy for the signed-out Persuade surface.
// Drawn from the real sections the app ships (Spec 000 / Spec 074); no
// testimonials, metrics, or security claims are invented on this surface.
export const LANDING = {
  skipToLogin: "跳到登入",
  skipToRegister: "跳到註冊表單",
  brandFull: "中國基督教播道會顯恩堂",
  brand: "顯恩堂",
  brandSystem: "系統",
  homeLabel: "顯恩堂系統首頁",
  systemDescription: "會友與教會同工的內部營運系統。",
  navLabel: "頁面導覽",
  featuresNav: "認識功能",
  loginNav: "登入",
  heroTitle: "一堂的相聚，有據可依",
  heroSub:
    "將課程報名、聚會管理、掃描簽到與關懷追蹤，收進同一本會友名冊——讓牧養有事可循，讓服事有據可查。",
  primaryCta: "立即登入",
  secondaryCta: "認識功能",
  registerTitle: "一本名冊，涵蓋一堂",
  registerLead: "以下都是顯恩堂系統實際提供的功能。",
  featurePrograms: "課程與活動",
  featureProgramsDesc: "活動與課程的報名、名單，一處掌握。",
  featureEvents: "聚會管理",
  featureEventsDesc: "定期聚會與日程安排，一目了然。",
  featureScanner: "掃描簽到",
  featureScannerDesc: "以 QR 碼即時記錄出席，無需手寫名單。",
  featureManagement: "管理工作區",
  featureManagementDesc: "審批、名冊與權限集中處理，一處掌控。",
  loginPanelLead: "使用你的用戶名稱與密碼。",
  loginAfterNote: "登入後，將進入你獲授權的功能頁面。",
  footerMotto: "一堂之務，一處安放。",
  footerNote: "顯恩堂系統 — 教會管理系統",
} as const;
