// Traditional Chinese copy for the shell (Spec 074 user story 29).
// Every user-facing string lives here; no hardcoded text in components.
export const COPY = {
  appName: "顯恩堂系統",
  // Official full church title used as the primary brand string in headers
  // (Spec 079 §1: shorter marks are legacy shorthand only).
  appFullName: "中國基督教播道會顯恩堂",
  skipToContent: "跳到主要內容",
  login: {
    title: "登入",
    upgradeTitle: "設定新密碼",
    usernameLabel: "用戶名稱",
    passwordLabel: "密碼",
    legacyPasswordLabel: "舊 PIN 碼",
    newPasswordLabel: "新密碼",
    submit: "登入",
    submitting: "登入中…",
    upgradeSubmit: "設定新密碼並登入",
    upgrading: "設定中…",
    error: "用戶名稱或密碼不正確。",
    upgradeRequired: "此帳戶需要先設定新密碼才能登入。",
    networkError: "無法連接伺服器，請檢查網路後再試。",
    success: "登入成功。",
  },
  profile: {
    title: "個人檔案",
    name: "姓名",
    username: "用戶名稱",
    phone: "電話",
    role: "角色",
    status: "狀態",
    qrCode: "QR Code",
    qrEmpty: "目前沒有 QR 資料。",
    accountSettings: "帳戶資料",
    accountSettingsHint: "更新用戶名稱或密碼。",
  },
  restore: {
    loading: "正在還原工作階段…",
    restored: "工作階段已還原。",
    expired: "工作階段已過期，請重新登入。",
  },
  logout: {
    submit: "登出",
    error: "登出時發生錯誤，但已安全終止工作階段。",
    failedNotice: "登出請求失敗，但本機工作階段已清除。",
    success: "已登出。",
    forbiddenAction: "登出並返回登入",
  },
  account: {
    updatedNotice: "帳戶資料已更新，請重新登入。",
  },
  sections: {
    profile: "個人檔案",
    programs: "課程與活動",
    events: "聚會管理",
    scanner: "掃描簽到",
    care: "關懷儀表板",
    permissions: "權限管理",
    // S10 heading: distinguishes the permissions SECTION label from the
    // page title (roles + permissions table, Spec #079 §S10).
    permissionsHeading: "權限與角色管理",
    placeholder: "內容建置中。",
  },
  nav: {
    backToHome: "返回首頁",
    backToProfile: "返回個人檔案",
    loading: "載入中…",
    unauthorized: "您沒有權限存取此頁面。",
    unknownRoute: "找不到此頁面。",
    label: "主要導航",
  },
  error: {
    networkError: "無法連接伺服器，請檢查網路後再試。",
    unavailable: "系統暫時無法使用，請稍後再試。",
    serverError: "伺服器發生錯誤，請稍後再試。",
    forbidden: "您沒有權限執行此操作。",
    validation: "輸入資料無效，請檢查後再試。",
    notFound: "找不到請求的資料。",
    conflict: "資料衝突，請重新整理後再試。",
    malformed: "伺服器回應格式錯誤。",
    unknown: "發生未知錯誤。",
    retry: "重試連接",
  },
  empty: {
    courseData: "目前沒有課程資料。",
    title: "無資料",
  },
  programs: {
    pageTitle: "課程與活動",
    lead: "先選部門，再處理課程、聚會或報名。",
    departments: "部門",
    programs: "課程與活動",
    modules: "模組",
    moduleDisabled: "此功能模組尚未啟用。請先啟用模組，相關功能才會顯示。",
    noDepartments: "目前沒有部門。新增部門後，就可以開始建立課程。",
    noPrograms: "此部門尚未有課程。啟用課程目錄後可新增。",
    createDepartment: "新增部門",
    createProgram: "新增課程",
    deptCode: "部門代碼",
    deptName: "部門名稱",
    deptCodePlaceholder: "例如：青區",
    deptNamePlaceholder: "部門名稱",
    programName: "課程名稱",
    programNamePlaceholder: "課程名稱",
    programDescription: "課程簡介",
    programCategory: "活動類別",
    programLifecycle: "課程狀態",
    programEnrollmentMode: "報名方式",
    programDisplayOrder: "顯示次序",
    programDetails: "查看課程詳情",
    programOverview: "概覽",
    programTasks: "課程工作",
    programEdit: "基本資料",
    programEvents: "聚會與時間表",
    programEnrollment: "報名",
    programLeaders: "事工負責人",
    backToOverview: "返回概覽",
    programDescriptionEmpty: "未填寫課程簡介。",
    editProgram: "編輯課程",
    saveProgram: "儲存課程",
    cancelEdit: "取消編輯",
    behaviorType: "形式",
    behaviorRecurring: "定期",
    behaviorOneOff: "單次",
    lifecycleDraft: "草稿",
    lifecyclePending: "籌備中",
    lifecycleActive: "啟用",
    lifecycleArchived: "已存檔",
    discoverabilityListed: "公開",
    discoverabilityUnlisted: "不公開",
    moduleProgramCatalog: "課程目錄",
    moduleEnrollment: "報名",
    moduleEvents: "聚會",
    moduleAttendance: "出席",
    moduleCustomForms: "自訂表單",
    enable: "啟用",
    disable: "停用",
    expand: "展開",
    collapse: "收合",
    submit: "建立",
    submitting: "建立中…",
    created: "已建立。",
    updated: "已更新。",
    loadError: "無法載入課程與活動資料，請稍後再試。",
    events: "聚會",
    eventsEmpty: "目前沒有聚會。",
    noRules: "尚未設定時間表。",
    eventDate: "日期",
    eventTime: "時間",
    eventStatus: "狀態",
    eventActive: "進行",
    eventCancelled: "已取消",
    eventScheduleSource: "自動",
    eventManualSource: "手動",
    hkTimeMarker: "時間均以香港時間顯示（GMT+8）。",
    ruleWeekly: "每週",
    ruleMonthly: "每月",
    dayOfWeekLabel: "每週日子",
    weekdaySunday: "星期日",
    weekdayMonday: "星期一",
    weekdayTuesday: "星期二",
    weekdayWednesday: "星期三",
    weekdayThursday: "星期四",
    weekdayFriday: "星期五",
    weekdaySaturday: "星期六",
    monthDayLabel: "每月日子",
    startTime: "開始時間",
    endTime: "結束時間",
    addRule: "新增時間表",
    generateEvents: "產生聚會",
    generating: "產生中…",
    generated: "已產生 {created} 場聚會，跳過 {skipped} 場重複。",
    generateRequiresRecurring: "只有定期課程可產生聚會。",
    createEvent: "新增聚會",
    eventStart: "開始時間（香港時間）",
    eventEnd: "結束時間（香港時間）",
    cancelEvent: "取消聚會",
    cancelEventConfirm: "確定取消這場聚會嗎？取消後仍會保留記錄。",
    confirmCancelEvent: "取消聚會",
    keepEvent: "保留聚會",
    cancelReason: "取消原因",
    cancelReasonPlaceholder: "請填寫取消原因",
    eventCancelledNotice: "聚會已取消。",
    cancelledReason: "取消原因：{reason}",
    rescheduleEvent: "改期",
    confirmReschedule: "確認改期",
    rescheduleStart: "改期開始時間",
    rescheduleEnd: "改期結束時間",
    cancelOccurrence: "取消該次",
    cancelOccurrenceConfirm: "確定取消這次聚會嗎？之後可以恢復。",
    confirmCancelOccurrence: "確定取消該次",
    keepOccurrence: "保留該次",
    restoreOccurrence: "恢復該次",
    exceptionUpdatedNotice: "已更新例外。",
    exceptionRemovedNotice: "已移除例外。",
    eventRescheduledBadge: "已改期至 {time}",
    eventCancelledBadge: "本次已取消",
    eventsLoadError: "無法載入聚會資料，請稍後再試。",
    ruleCreateError: "無法新增時間表。",
    exceptionCreateError: "無法更新例外。",
    eventCreateError: "無法新增聚會。",
    generateError: "無法產生聚會。",
    enrollment: "報名",
    enrollmentModeMemberRequest: "成員申請",
    enrollmentModeManagerOnly: "管理員安排",
    requestEnroll: "申請報名",
    requestSubmitted: "已送出報名申請。",
    withdrawRequest: "撤回申請",
    requestWithdrawnNotice: "申請已撤回。",
    requests: "報名申請",
    noRequests: "目前沒有報名申請。",
    requestPending: "待處理",
    requestApproved: "已核准",
    requestRejected: "已拒絕",
    requestWithdrawn: "已撤回",
    requestSubmittedAt: "申請日期",
    approve: "核准",
    reject: "拒絕",
    decisionNote: "決定備註",
    decisionMade: "已處理申請。",
    enrollments: "報名記錄",
    noEnrollments: "目前沒有報名記錄。",
    enrollmentActive: "已加入",
    enrollmentCancelled: "已取消",
    cancelEnrollment: "取消報名",
    enrollmentCancelledNotice: "報名已取消。",
    assistedEnroll: "新增報名",
    memberId: "成員 ID",
    memberIdPlaceholder: "輸入姓名或用戶名稱",
    memberSearchHint: "輸入姓名或用戶名稱，從現有會友中選擇。",
    memberSearchLoading: "搜尋會友中…",
    memberSearchError: "暫時無法搜尋會友，請稍後再試。",
    memberSearchRetry: "重試搜尋",
    memberSearchEmpty: "找不到符合的現有會友。",
    memberSearchResults: "找到 {count} 位會友。",
    clearMember: "清除選擇",
    assistedSubmitted: "已新增報名。",
    managerOnlyNote: "此課程由管理員安排成員加入。",
    selfEnrollmentNote: "你已加入此課程。",
    enrollmentError: "報名操作失敗。",
    leaders: "事工負責人",
    noLeaders: "目前沒有事工負責人。",
    assignLeader: "新增負責人",
    revokeLeader: "移除負責人",
    confirmRevokeLeader: "確定要移除此事工負責人嗎？",
    confirmRevoke: "確定移除",
    cancelRevoke: "取消",
    leaderUserId: "選擇會友",
    leaderUserIdPlaceholder: "輸入姓名或用戶名稱",
    leaderAssignedNotice: "已新增事工負責人。",
    leaderRevokedNotice: "已移除事工負責人。",
    leaderAccountInactive: "無法新增：此帳戶尚未啟用。請選取狀態為「啟用」的帳戶。",
    enrollmentDuplicate: "此會友已報名此課程。",
  },
} as const;

export function errorCopyFor(
  code?: string,
  // _detail reserved for future fallback; centralized copy is the sole user-facing source.
  _detail?: string
): string {
  if (code === "NETWORK_ERROR") {
    return COPY.error.networkError;
  }
  if (code === "AUTH_REQUIRED") {
    return COPY.restore.expired;
  }
  if (code === "FORBIDDEN") {
    return COPY.error.forbidden;
  }
  if (code === "VALIDATION") {
    return COPY.error.validation;
  }
  if (code === "NOT_FOUND" || (code && code.endsWith("_NOT_FOUND"))) {
    return COPY.error.notFound;
  }
  if (code === "CONFLICT") {
    return COPY.error.conflict;
  }
  if (code === "ACCOUNT_INACTIVE") {
    return COPY.programs.leaderAccountInactive;
  }
  if (code === "ENROLLMENT_DUPLICATE") {
    return COPY.programs.enrollmentDuplicate;
  }
  if (code === "UNAVAILABLE") {
    return COPY.error.unavailable;
  }
  if (code === "INTERNAL_ERROR") {
    return COPY.error.serverError;
  }
  if (code === "MALFORMED_RESPONSE" || code === "MALFORMED_REQUEST") {
    return COPY.error.malformed;
  }
  return COPY.error.unknown;
}

// Traditional Chinese landing-page copy for the signed-out Persuade surface.
// Drawn from the real sections the app ships (Spec 000 / Spec 074); no
// testimonials, metrics, or security claims are invented on this surface.
export const LANDING = {
  skipToLogin: "跳到登入",
  skipToRegister: "跳到註冊表單",
  brandFull: "中國基督教播道會顯恩堂",
  brand: "顯恩堂",
  brandSystem: "系統",
  homeLabel: "顯恩堂系統首頁",
  navLabel: "頁面導覽",
  featuresNav: "認識功能",
  loginNav: "登入",
  heroTitle: "一堂的相聚，有據可依",
  heroSub:
    "將課程報名、聚會管理、掃描簽到與關懷追蹤，收進同一本會友名冊——讓牧養有事可循，讓服事有據可查。",
  primaryCta: "立即登入",
  secondaryCta: "認識功能",
  registerTitle: "一本名冊，涵蓋一堂",
  registerLead: "以下都是顯恩堂系統實際提供的功能。",
  featurePrograms: "課程與活動",
  featureProgramsDesc: "活動與課程的報名、名單，一處掌握。",
  featureEvents: "聚會管理",
  featureEventsDesc: "定期聚會與日程安排，一目了然。",
  featureScanner: "掃描簽到",
  featureScannerDesc: "以 QR 碼即時記錄出席，無需手寫名單。",
  featureCare: "關懷儀表板",
  featureCareDesc: "把需要跟進的會友，放在事奉者眼前。",
  loginPanelLead: "使用你的用戶名稱與密碼。",
  loginAfterNote: "登入後，將進入你獲授權的功能頁面。",
  footerMotto: "一堂之務，一處安放。",
  footerNote: "顯恩堂系統 — 教會管理系統",
} as const;
