export type PresentationScreenLifecycle = "active" | "historical" | "planned";

export interface PresentationScreenCatalogEntry {
  readonly screenId: string;
  readonly productFamily: string;
  readonly lifecycle: PresentationScreenLifecycle;
  readonly primaryBaselinePsn: string;
  readonly route: string | null;
  readonly intent: string | null;
  readonly gap: string | null;
  readonly supersedes: readonly string[];
}

/**
 * Governance-owned screen obligations. Story declarations are discovered
 * separately and joined to these obligations by the Storybook catalog.
 */
export const PRESENTATION_SCREEN_CATALOG = [
  {
    screenId: "management-hub",
    productFamily: "management",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-HUB-DEFAULT",
    route: "/management",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "auth-sign-in",
    productFamily: "public-auth-member-communications",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-AUTH-SIGN-IN-DEFAULT",
    route: "/",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "auth-register",
    productFamily: "public-auth-member-communications",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-AUTH-REGISTER-DEFAULT",
    route: "/register",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "member-home",
    productFamily: "public-auth-member-communications",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MEMBER-HOME-DEFAULT",
    route: "/home",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "member-profile",
    productFamily: "public-auth-member-communications",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MEMBER-PROFILE-DEFAULT",
    route: "/profile",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "member-account-settings",
    productFamily: "public-auth-member-communications",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MEMBER-ACCOUNT-SETTINGS",
    route: "/profile/settings",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "communications-notices",
    productFamily: "public-auth-member-communications",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-COMMS-NOTICES-DEFAULT",
    route: "/notices",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "communications-messages",
    productFamily: "public-auth-member-communications",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-COMMS-MESSAGES-DEFAULT",
    route: "/messages",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "public-not-found",
    productFamily: "public-auth-member-communications",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PUBLIC-NOT-FOUND",
    route: null,
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-management-directory",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-MANAGEMENT-DIRECTORY",
    route: "/programs",
    intent: "mode=management",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-participant-directory",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-PARTICIPANT-DIRECTORY",
    route: "/programs",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-participant-event-detail",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-PARTICIPANT-EVENT-DETAIL",
    route: "/programs",
    intent: "program=t07-3-program&event=t07-3-event",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-participant-program-detail",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-PARTICIPANT-PROGRAM-DETAIL",
    route: "/programs",
    intent: "program=t07-3-program",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-workspace-events",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-WORKSPACE-EVENTS",
    route: "/programs",
    intent: "mode=management&program=t07-3-program&task=events",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-workspace-notifications",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-WORKSPACE-NOTIFICATIONS",
    route: "/programs",
    intent: "mode=management&task=notifications",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-workspace-overview",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-WORKSPACE-OVERVIEW",
    route: "/programs",
    intent: "mode=management&program=t07-3-program",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-workspace-participants",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-WORKSPACE-PARTICIPANTS",
    route: "/programs",
    intent: "mode=management&program=t07-3-program&task=participants",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "programs-workspace-settings",
    productFamily: "programs",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-PROGRAMS-WORKSPACE-SETTINGS",
    route: "/programs",
    intent: "mode=management&program=t07-3-program&task=settings",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-registrations-fallback",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-REGISTRATIONS-FALLBACK",
    route: "/registrations",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-account-access",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-ACCOUNT-ACCESS",
    route: "/management",
    intent: "module=accounts&account=t07-4-account&view=access",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-account-directory",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-ACCOUNT-DIRECTORY",
    route: "/management",
    intent: "module=accounts",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-approval-detail",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-APPROVAL-DETAIL",
    route: "/management",
    intent: "module=approvals&request=t07-4-registration",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-approval-queue",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-APPROVAL-QUEUE",
    route: "/management",
    intent: "module=approvals",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-checkin-settings",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-CHECKIN-SETTINGS",
    route: "/management",
    intent: "module=checkin-settings",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-home-cms",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-HOME-CMS",
    route: "/management",
    intent: "module=home-content",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-member-directory",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-MEMBER-DIRECTORY",
    route: "/management",
    intent: "module=members",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "identity-permission-editor",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-IDENTITY-PERMISSION-EDITOR",
    route: "/management",
    intent: "module=permissions",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "identity-role-hierarchy",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-IDENTITY-ROLE-HIERARCHY",
    route: "/management",
    intent: "module=roles",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-settings-hub",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-SETTINGS-HUB",
    route: "/management",
    intent: "module=settings",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "management-timezone-settings",
    productFamily: "management-identity",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-MGMT-TIMEZONE-SETTINGS",
    route: "/management",
    intent: "module=timezone-settings",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "attendance-assisted-check-in",
    productFamily: "attendance-scanner-guest",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-ATTENDANCE-ASSISTED-CHECK-IN",
    route: "/scanner",
    intent: "mode=assisted&event=t07-5-event",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "attendance-operator",
    productFamily: "attendance-scanner-guest",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-ATTENDANCE-OPERATOR",
    route: "/events",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "attendance-operator-roster",
    productFamily: "attendance-scanner-guest",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-ATTENDANCE-OPERATOR-ROSTER",
    route: "/events",
    intent: "event=t07-5-event",
    gap: null,
    supersedes: [],
  },
  {
    screenId: "attendance-guest-check-in",
    productFamily: "attendance-scanner-guest",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-ATTENDANCE-GUEST-CHECK-IN",
    route: "/guest-check-in",
    intent: null,
    gap: null,
    supersedes: [],
  },
  {
    screenId: "attendance-scanner-boundary",
    productFamily: "attendance-scanner-guest",
    lifecycle: "active",
    primaryBaselinePsn: "PSN-ATTENDANCE-SCANNER-BOUNDARY",
    route: "/scanner",
    intent: "mode=self",
    gap: null,
    supersedes: [],
  },
] as const satisfies readonly PresentationScreenCatalogEntry[];
