import react from "@vitejs/plugin-react";
import { defineProject } from "vitest/config";

export default defineProject({
  plugins: [react()],
  resolve: {
    alias: { "@": import.meta.dirname ?? "" },
  },
  test: {
    testTimeout: 30_000,
    hookTimeout: 30_000,
    environment: "jsdom",
    include: [
      "lib/app.test.tsx",
      "lib/sections.test.ts",
      "lib/api.test.ts",
      "lib/navigation-controller.test.ts",
      "lib/registration.test.tsx",
      "lib/approval-queue.test.tsx",
      "lib/approval-detail.test.tsx",
      "lib/section-view.test.tsx",
      "lib/account-settings.test.tsx",
      "lib/home.test.tsx",
      "lib/hk-time.test.ts",
      "lib/messages-intent.test.ts",
      "lib/messages-panel.test.tsx",
      "lib/management-hub.test.tsx",
      "lib/settings-hub.test.tsx",
      "lib/permissions-panel.test.tsx",
      "lib/member-directory-panel.test.tsx",
      "app/management/home-cms-editor.test.tsx",
      "lib/qr-code.test.tsx",
      "lib/programs/programs-events-panel.test.tsx",
      "lib/programs/programs-enrollment-panel.test.tsx",
      "lib/programs/programs-leaders-panel.test.tsx",
      "lib/programs/member-picker.test.tsx",
      "lib/programs/programs-boundary.test.tsx",
      "lib/programs/programs-attention.test.tsx",
      "lib/programs/programs-notifications.test.tsx",
      "lib/programs/participant-directory.test.tsx",
      "lib/programs/management-directory.test.tsx",
      "lib/programs/program-form.test.tsx",
      "lib/programs/department-settings-panel.test.tsx",
      "lib/programs/program-settings.test.tsx",
      "lib/programs/program-workspace.test.tsx",
      "lib/programs/programs-management-boundary.test.tsx",
      "lib/programs/event-detail.test.tsx",
      "lib/session-deep-link.test.tsx",
      "lib/programs/participant-program-detail.test.tsx",
      "lib/programs/participant-enrollment.test.tsx",
      "lib/attendance-panel.test.tsx",
      "lib/attendance-operator-panel.test.tsx",
      "lib/attendance-roster.test.tsx",
      "lib/self-check-in-panel.test.tsx",
      "lib/use-qr-camera.test.tsx",
      "lib/scanner-intent.test.ts",
      "lib/assisted-scanner-panel.test.tsx",
      "lib/scanner-boundary.test.tsx",
      "lib/notices-panel.test.tsx",
    ],
    setupFiles: ["./lib/test-setup.ts"],
    server: {
      deps: { inline: ["@testing-library/user-event"] },
    },
  },
});
